### ISSUE TITLE
MinExpEntStairDemo.m: `quse_subset_perc' undefined near line 291 column 22

### ISSUE THREAD

**Issue by yarikoptic** [Psychtoolbox-3/Psychtoolbox-3#138]
```
$> octave --no-init-file --eval "addpath (genpath (\"$PWD/../../Psychtoolbox\")); addpath(\"$PWD/../../Psychtoolbox/PsychBasic/Octave3LinuxFiles/\"); MinExpEntStairDemo"                     
GNU Octave, version 3.6.2                                                                                                                                                
Copyright (C) 2012 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type `warranty'.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at http://www.octave.org.

Please contribute if you find this software useful.
For more information, visit http://www.octave.org/help-wanted.html

Read http://www.octave.org/bugs.html to learn how to submit bug reports.

For information about changes from previous versions, type `news'.

warning: function /usr/share/octave/packages/statistics-1.1.3/fstat.m shadows a core library function
warning: nested functions are coerced into subfunctions in file /home/yoh/deb/perspect/psychtoolbox/psychtoolbox-3/Psychtoolbox/PsychDemos/../../Psychtoolbox/PsychStairCase/MinExpEntStair.m
error: `quse_subset_perc' undefined near line 291 column 22
error: called from:
error:   /home/yoh/deb/perspect/psychtoolbox/psychtoolbox-3/Psychtoolbox/PsychDemos/../../Psychtoolbox/PsychStairCase/MinExpEntStair.m at line 291, column 19
error:   /home/yoh/deb/perspect/psychtoolbox/psychtoolbox-3/Psychtoolbox/PsychDemos/MinExpEntStairDemo.m at line 41, column 1
```

**Comment by dcnieho** [comment]
@kleinerm, you spoke of possibly allowing classdef programming in PTB. Would this staircase "class" be a candidate? I.e., would you include it if i make a classdef version of it? I foresee no interface changes, so it should not be a breaking change.

**Comment by kleinerm** [comment]
Yes. It doesn't work on Octave atm. so it can only become better with OOP, right?
You can install Octave-4 64-Bit for Windows and then give it a go. It's not at the same level as current Matlab afaik, but basic stuff seems to work well. I just converted a PacMan "game" (well its serious science, using PacMan to implement the paradigm) written by a friend, apparently using R2012b or later. Conversion of that one with multiple classes, getter/setter methods etc. was done quite quickly. One important thing seems to be to terminate definition of member variables in classes with ; otherwise Octave chokes, whereas Matlab accepts that. Not sure if this is a Octave limitation, or actually wrong code that Matlab just lets pass leniently. I suspect the weak spots in Octave are when it comes to some kind of event handling, but i don't have any experience with that.

**Comment by dcnieho** [comment]
Cool, I'll add it to the todo list. classdef is kinda new to me, so I'm
going to take my time for it, use it as a learning experience. Will indeed
test on Octave 4 (or perhaps do the testing there and then check how it
runs on matlab.

**Comment by kleinerm** [comment]
Diederick ported MinExtEntStair[Demo] to classdef and now it works with both Matlab & Octave,
so this issue is now a non-issue. Thanks!
