### ISSUE TITLE
Function reference offline

### ISSUE THREAD

**Issue by matsvanes** [Psychtoolbox-3/Psychtoolbox-3#235]
It seems that the function reference has been offline for a while?

**Comment by kleinerm** [comment]
Fixed by the magnificent towolf - for now. The function reference is unfortunately hosted on a Apple OSX system, and OSX apparently not only sucks for neuro-science applications but also for web serving. Apparently whenever that machine gets rebooted or upgraded, it resets some of its web server configuration and kills off the function reference which needs some non-standard configuration. So expect this failure to recur frequently until we manage to move the function reference to a more competent hosting service.
