### ISSUE TITLE
DotDemo

### ISSUE THREAD

**Issue by dbphi6** [Psychtoolbox-3/Psychtoolbox-3#246]
If I run DotDemo on my MacBookPro running Yosemite 10.10.3 and I press any key to terminate, the screen only goes blank and does not return to the MatLab screen. Is there some compatibility issue here with Yosemite?

**Comment by iandol** [comment]
Have you installed the kernel extension? Does pressing the mouse buttons return you to your normal display? Can you capture any errors on the MATLAB command line?

DotDemo works fine on my Macbook Pro running 10.10.4 public beta and MATLAB 2015a, but remember you may need to switch display resolutions to stop sync errors at least (I use SwitchResX which binds keystrokes to the 4 main HiDPI resolution modes so it makes it very quick to switch).

**Comment by kleinerm** [comment]
That black screen at the end is "normal" - yet another bug in the OSX operating system, i think since at least 10.9. A mouse click brings the display back. Other than that follow Ian's advice.

**Comment by dbphi6** [comment]
Thanks very much indol and kleinerm (real names unknown!) for your excellent advice. Yes - a mouse click does bring back the display (and there are no errors on the MatLab command line) - but it should not need it - correct? I used the DotDemo as a way to explain that Screen('CloseAll') does not seem to work in my actual programs. iandol's suggestion was to install the kernel extension - I tried this but I don't think I got it to work - is there a good website that explains this? I don't quite understand what the kernel extension does. As to the display resolution - how would I do this and, if I did, would it not affect the display of the images in the experiments? My previous MacBookPro ran under Snow Leopard and my programs ran well on that. Would it be better to uninstall Yosemite and substitute it with that older operating system? Once again, thanks.

**Comment by kleinerm** [comment]
If Apple would make less buggy operating systems, you should not need that click, but in reality you do. There's a Screen preference setting to change the way we open fullscreen windows which fixes that problem but directly violates Apples advice on how to get good performance, iow. you replace the black screen bug by potential new timing bugs. The kernel extension "help PsychtoolboxKernelDriver" - but wouldn't help against the black screen. For display resolution other than native one, see "help PanelFitterDemo". Other than that check the GitHub issue about "OSX 10.10 Yosemite" compatibility for tips on how to work around and check for various other OSX 10.10 brokeness.

Snow Leopard was the last OSX version which wasn't awful for vision science. But downgrading to that doesn't make much sense either, because it is unsupported by current PTB, unsupported by Apple wrt. bug fixes and security updates, and probably won't install or work on modern Macs anyway. Upgrading to Linux is recommended if you care for precision and reliability and best support. Other than that OSX 10.8 was at least bearable iirc, but i don't know how long we will continue to support that with PTB - depends on what kind of changes Apple will force on us with their next OSX release and if supporting 10.8 (or 10.9) would become difficult.
