### ISSUE TITLE
Should be able to update with git

### ISSUE THREAD

**Issue by hyiltiz** [Psychtoolbox-3/Psychtoolbox-3#250]
Google Code is shut down and now that almost all code and development as well as releases happen at Github, it should be possible to update using Github via git. 

I assume this has been proposed (though I could not find it from within the issue list), and the possible risk will be that a simple `git pull` might not be what we want. One might want to `rebase` the target release on top of the installed release, though.

**Comment by dcnieho** [comment]
If you're still havign a google code-based PTB, you need to reinstall,
gettign a fresh copy of downloadpsychtoolbox from the website. This indeed
uses github for install and update

**Comment by hyiltiz** [comment]
​But downloadPsychToolbox calls svn rather than git.​

**Comment by dcnieho** [comment]
Ah sorry, i missed the "via git" part. What would that add over the current
workflow for the end user?

**Comment by hyiltiz** [comment]
​Given that over the past three years, git (and presumable hg) has almost
completely taken over svn​, git has much more users than svn. I, for
example, really would appreciate it if we could simply use the both svn and
git for the process, since installing svn in a system where git exists
seems a bit absurd. Maybe use `git svn` in the system if git is present?

**Comment by iandol** [comment]
I only use git to keep my PTB up-to-date, as easy as fork/clone and pull -- this already works fine (and SetupPsychtoolbox.m in matlab on the first use). The major downside is the huge amount of space the .git folder takes up with a clone which is unnecessary for most users. I'm sure it is easyish to modify the download script to use [git instead of svn](https://github.com/iandol/Psychtoolbox-3/blob/master/Psychtoolbox/DownloadPsychtoolbox.m#L743), but most PTB users have probably already installed svn, so in legacy terms it makes sense to stick to that?

**Comment by hyiltiz** [comment]
​It surely makes sense to keep the old svn support since most PTB users
might have downloaded it via svn. Git clone and pull model is not feasible
for distributing releases since, as you pointed out, the .git folder has
the complete development history which is meaningless for end-users. Would
be nice to only update the changed files from one version to another,
though. While this could be done via git​, it is not necessarily the only
tool. For example, upon update request by an end-user, the user could
provide their tag/hash and we could do a quick check-up of the introduced
changes on the server side, and only download the changed files (if, better
with git, could be done by only downloading the patches, though).

Am I complicating stuff?

**Comment by iandol** [comment]
Well the [download](https://github.com/kleinerm/Psychtoolbox-3/blob/master/Psychtoolbox/DownloadPsychtoolbox.m) and [update](https://github.com/kleinerm/Psychtoolbox-3/blob/master/Psychtoolbox/UpdatePsychtoolbox.m) scripts are easy to read through, do you think it is worth refactoring them to use git and could you ensure an easy transition for existing users? I suspect this would be a good thing to do, but imagine it is way down on most people's priority list... One would also need to work out the details of how git can deploy a codebase and update it without cloning it, I'm sure this is possible but I have little idea what the best mechanism is.

**Comment by hyiltiz** [comment]
​Based on the UpdatePsychtoolbox.m code, we could do the following:

   1. check whether svn or git exists;
   2. if svn exists in the system, stick to the old code;​
   3. if only git exists, use here-to-be-implemented git update code;
   4. if none exists, one should simply install either svn or git;
   5. here-to-be-implemented:
   6. In the Contents.m file under the PsychtoolboxRoot, we could record
   the hash number as well as the version tag (I am not aware this is recorded
   anywhere in the downloaded package except the file name)
   7. Parse the Contents.m file for the hash: hash_current, and set the
   target tree-ish (e.g. branch name) hash_target: beta (to update to beta
   release)
   8.

   The command we then can use is essentially something like this; git
archive --output=changedFiles.zip HEAD $(git diff --name-only
hash_current hash_target)

   9. Then extract the changedFiles.zip and replace the old files with new
   ones.

This should work even if the original Psychtoolbox was manually downloaded
from a browser, or downloaded using svn, as long as git is present in the
system, and we can figure out a way to get the current hash (log it in the
Content.m file in each release).

I think this is a robust way of doing it. Apart form that, a relatively
newly implemented git feature called *shallow* clones also allows a simply
git clone and pull, but only since Git 1.9 with a line like this:

$git clone *-depth 1 *--branch beta -- repo_url directory

$git pull origin beta

This could be a better solution. But since it is a fairly new feature, I
believe this could wait for some time.

**Comment by dcnieho** [comment]
Hi,

While i'm not immediately against it, it sounds rather complicated, error
prone, and a lot extra to maintain. What problem are we solving with this?
Also, I'd say the 1.9+ shallow clone is the way to go as it is much
simpler. Using that, things are not more complicated than issuing a
different command during install (And the update script will have to see
whether the current checkout is svn or git). I see little value in the
effort required to implement the method with the hash (also, how are you
going to commit the hash if the hash is only known after the commit, and
adding it in file and committing again changes the hash)? If people are
using svn, they can keep on using it with no issue, and if people have a
manual download without version info then they'll have to reinstall
(perhaps the updater should catch this case  based on the svn/git return
error code (see
https://subversion.apache.org/docs/api/1.8/svn__error__codes_8h_source.html
for svn error codes) and automatically call DownloadPsychtoolbox to
reinstall).

All in all, i think we'd welcome patches for using git shallow clones
(though note Mario is very much the one to decide upon this, not me), but
i'd like to keep it restricted to cases where svn is not available only, so
we stick with the process we know well when possible.

All the best,
Dee

**Comment by kleinerm** [comment]
I don't know. I definitely wouldn't want to have that fragile < 1.9 stuff. The shallow clone method might be ok and simple enough to integrate reliably. However, the download size/on-disc size doubles compared to the current svn checkout - you get the .git and PsychSourceGL folders regular users don't care about, so we go from some 143 MB ot 247 MB for no real gain for users. At the same time the shallow checkout doesn't provide the git history before the checkout point, so potentially valuable "undo" options like going to arbitrary revision numbers or previous releases in UpdatePsychtoolbox would not work. On recent Linux distros we have git 1.9, probably also on OSX didn't test. On Windows git is not a tool typically installed, so the need to install something before you can install doesn't disappear.

The only advantage i can really see is that PsychtoolboxVersion would actually provide a commit id we can use to find out which version the user reporting a bug has. Indeed PTB contains a command GetGITInfo for just that if one works on a git clone instead of svn. Currently i can't map revision numbers back to git commits. I'd need to have a parallel svn checkout to manually match svn revision -> git commit, which i don't actually do.

But other than that i can't quite see the advantage over our current method for users. So i don't know. As an optional alternative method to svn, the git shallow method is maybe ok. Although i'd assume that users which want to take advantage of git's goodies would simply clone our git repo completely, at the cost of about 1.2 GB of data on their disk.

One of the advantages of git over subversion is that git keeps everything local and doesn't depend on a central server for the whole project history. Good for development. From our users perspective, most of which are just consumers of code and not developers, the advantage of subversion would be that they can move through project history in the rare occasions when they need that, but don't have to pay the local storage costs if they don't need that.

**Comment by hyiltiz** [comment]
Okay, you have completely persuaded me. So from a user's perspective, there
would not be must advantage. But thanks very much for your thorough
consideration!
