### ISSUE TITLE
Matlab crashes due to driver.

### ISSUE THREAD

**Issue by EmmaRenauld** [Psychtoolbox-3/Psychtoolbox-3#275]
Hi,

I am experiencing many troubles installing psychtoolbox on my new computer. I have looked on many forums and tried many things without success. I really hope there are solutions other then «Get a new computer» or «Get linux», because this computer is not mine!

Infos:
- Computer: Windows 8.1, HP Probook
- Graphic card: AMD Radeon and Intel.
- Matlab: I tried both 2013a and 2015a.

Problem:
- With AMD: ScreenTest ends with a synchronisation failure. 
==> I read help SyncTrouble. I tried most of what it says: updated drivers. Set «Vertical refresh» to «always on». Set tripple buffering to off. I tried running the screenTest with verbosity 10, but there is no real information about the bug. Only a warning about DWM not being disabled.

==> If I force matlab to use Intel instead (using the «power saving» in switchable graphics), it still doesn't work.

==> If, again with Intel, I also choose «disable display scaling on high DPI level» in matlab's properties, it works, but only once, and only with matlab 2013. 
- With matlab 2015, matlab crashes right away. Error title on the log file is «Access violation».
- With matlab 2013, the first call to any Psychtoolbox script (ex, ScreenTest or OSXCompositorIdiocyTest) works perfectly. The second makes matlab crash. The error log file has the title «Segmentation violation ». With verbosity 10, the following message is sent:
PTB-INFO: VBL startline = 1080 , VBL Endline = 1080
The detected endline of the vertical blank interval is equal or lower than the startline. This indicates that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps for it.  […] Read 'help BeampositionQueries'. […] Read  'help ConserveVRAMSettings', section 'kPsychUseBeampositionQueryWorkaround'.

==> I tried using VRAMSettings with 4096, it still doesn't work. I tried using Screen('Preference', 'VBLEndlineOverride', VTOTAL); but I don't know what VTOTAL to use.

==> I tried with an external screen. Still didn't work.

Anything else is way passed my poor knowledge of drivers. PLEASE help me understand what other steps I could try!! 

Thank you very much!

Emmanuelle

**Comment by suxpert** [comment]
PTB claimed that Windows 8+ is `partially supported`. According to MSDN, there's no way to disable DWM on windows 8+, however PTB do not like DWM :)

PTB also claimed that hybrid-graphics is a bad choice (Although most PCs are hybrid graphics nowadays because of Intel CPU).

Here is what I meet and you may find out that there are no simple way to **fix** such issue:

In my lab, there are 4 laptops, 3 Lenovo L440 with GeForce GT 720M, 1 T440 with GeForce GT 730M.

Two of the L440 have installed windows server 2012 r2, running Matlab 2012b x64, PTB works very well on one of them, but not so well on the other one. Another L440 have installed windows 10, running the same version of Matlab, now PTB can not even pass the ScreenTest.

If I use matlab/octave in Ubuntu 14.04LTS (the windows 10 laptop), PTB works like a charm.

On the T440 with better Graphic card 730M, windows 7 x64, PTB can pass the ScreeTest at 50% level. But if I boot it to Kubuntu (14.04LTS), PTB will probably failed the test.

So my suggestion is, perhaps you can choose a different OS (e.g., downgrade to windows 7, dual boot a Linux), replace the graphic card, or wait for a new driver... But you know, `No Silver Bullet`, perhaps none of them works, or even perhaps it may work after you plug in a different power.

**Comment by kleinerm** [comment]
Emmanuelle, didn't you report in PTB forum message 19576 that your problem is resolved? Was that incorrect?
@suxpert, so your failure on KUbuntu with the 730M, is this with nouveau or with the NVidia proprietary driver? Is this also a hybrid-graphics laptop?

**Comment by EmmaRenauld** [comment]
Hi. Indeed, I reported it worked, and it was true. But I had not realized it only worked for a few times, before matlab would crash.

Now I installed windows 7 instead, and once again Intel works better than AMD. We will see in the next days how it goes.

**Comment by kleinerm** [comment]
Ok, that crashing of Matlab is strange, probably a graphics driver bug then. As i said, the failure of AMD on the Internal laptop flat panel is not unexpected at all. That's expected for certain types of hybrid-graphics laptops. Have you tried if the AMD works instead on the external video output (and then Intel potentially fails)? It would be interesting to see how a recent Linux copes with your Laptop. Unfortunately i currently don't have access to a suitable hybrid graphics laptop to test (or help improve) Linux hybrid graphics support. My participation in Linux hybrid-graphics related development was for some sub-components of the system that are required for hybrid-graphics to work better at some point, but which don't require one to actually have such a laptop to develop and test. Supporting hybrid graphics with robust timing is unfortunately technically rather involved, so progress is slow.

Another cause of the crash could be related not to the hybrid-graphics bits, but to the HiDPI panel. Maybe different versions of Matlab declare different levels of HiDPI support to the OS, so get treated differently. The way current Windows versions implement HiDPI support could make this rather difficult - or borderline impossible - for us to deal with properly as well, if visual timing is a concern.

**Comment by kleinerm** [comment]
Emma, could you test this Screen mex file:

https://github.com/kleinerm/Psychtoolbox-3/raw/37477288f2bc4f8edfce950190bdd0e73cf5b8ba/Psychtoolbox/PsychBasic/MatlabWindowsFilesR2007a/Screen.mexw64

1. Start Matlab on your Windows 8.1 system, although Windows 7 results would also be of some use.
2. PsychTweak('ScreenVerbosity', 4);
3. Screen Version
4. Tell me the output it prints.

I try to find out if i can improve HiDPI display handling for high resolution displays.

**Comment by EmmaRenauld** [comment]
Hi,



Here is the Screen Version output on windows 7: I don't have windows 8.1 anymore.



     version: '3.0.12.408987567'
       major: 3
       minor: 0
       point: 12
       build: 408987567
        date: 'Sep 21 2015'
        time: '15:39:27'
      module: 'Screen'
     project: 'OpenGL Psychtoolbox'
          os: 'Microsoft Windows'
    language: 'Matlab 64-Bit'
     authors: [1x7 struct]


I am not sure how to use the mex file, however. I copied it in Psychtoolbox/PsychBasic/MatlabWindowsFilesR2007a/. Is that it?
?

Don't hesitate to ask if I may be of any help,


Emmanuelle

p.s.  Now (with windows 7):

 - AMD (HiDPI or not): ScreenTest stops with error
PTB-INFO: OpenGL-Renderer is ATI Technologies Inc. :: AMD Radeon HD 8750M :: 4.4.13085 Compatibility Profile Context 14.301.1003.1007
WARNING: Couldn't compute a reliable estimate of monitor refresh interval! Trouble with VBL syncing?!?
----- ! PTB - ERROR: SYNCHRONIZATION FAILURE ! ----


-  Intel: (HiDPI or not)  ScreenTest works most of the time
        PTB-INFO: OpenGL-Renderer is Intel :: Intel(R) HD Graphics 4600 :: 4.0.0 - Build 9.18.10.3220
        PTB-INFO: VBL startline = 1080 , VBL Endline = 1080
        PTB-INFO: Measured monitor refresh interval from beamposition = 16.663167 ms [60.012601 Hz].
        PTB-INFO: Will use beamposition query for accurate Flip time stamping.
        PTB-INFO: Measured monitor refresh interval from VBLsync = 16.662817 ms [60.013861 Hz]. (50 valid samples taken, stddev=0.061602 ms.)
        PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
        PTB-INFO: Small deviations between reported values are normal and no reason to worry.

      With some exceptions:
        WARNING: Mismatch between measured monitor refresh intervals! This indicates problems with rasterbeam position queries.
        ----- ! PTB - WARNING: SYNCHRONIZATION TROUBLE ! ----
        One or more internal checks (see Warnings above) indicate that
        queries of rasterbeam position are not properly working for your setup.

        Psychtoolbox will work around this by using a different timing algorithm,
        but it will cause Screen('Flip') to report less accurate/robust timestamps
        for stimulus timing.

    Sometimes, matlab crashes.


________________________________
De : Mario Kleiner <notifications@github.com>
Envoyé : 22 septembre 2015 06:52
À : Psychtoolbox-3/Psychtoolbox-3
Cc : Emmanuelle Renauld
Objet : Re: [Psychtoolbox-3] Matlab crashes due to driver. (#275)


Emma, could you test this Screen mex file:

https://github.com/kleinerm/Psychtoolbox-3/raw/37477288f2bc4f8edfce950190bdd0e73cf5b8ba/Psychtoolbox/PsychBasic/MatlabWindowsFilesR2007a/Screen.mexw64

  1.  Start Matlab on your Windows 8.1 system, although Windows 7 results would also be of some use.
  2.  PsychTweak('ScreenVerbosity', 4);
  3.  Screen Version
  4.  Tell me the output it prints.

I try to find out if i can improve HiDPI display handling for high resolution displays.

-

**Comment by kleinerm** [comment]
I meant the output when you executed PsychTweak('ScreenVerbosity', 4); first. But i just ran that on a Windows-7 system here with Matlab R2014a, so i probably already know what it will do.

Windows 8.1 and 10 is very different in HiDPI display handling from older Windows versions like Vista, 7 and 8, that's why Windows 8.1 would have been interesting.

But anyway, am i right that you don't get problems related to the HiDPI display on your Windows-7? Thinking about it, i would expect that those problems are solved because PTB will disable the DWM on Windows-7, so it can't screw up due to HiDPI displays. It should probably be only a problem on Windows-8 and later, where PTB can't disable the DWM, so HiDPI displays will trigger additional complications.

The sync trouble you showed above for AMD is very likely caused by the hybrid graphics. But the Intel results look good to me. Maybe the Matlab crash is caused by yet another graphics driver bug in the Intel drivers.

**Comment by EmmaRenauld** [comment]
?Hi,


Yes, That is exactly what I gave you:

>> PsychTweak('ScreenVerbosity', 4);
>> Screen Version

ans =

     version: '3.0.12.408987567'
       major: 3
       minor: 0
       point: 12
       build: 408987567
        date: 'Sep 21 2015'
        time: '15:39:27'
      module: 'Screen'
     project: 'OpenGL Psychtoolbox'
          os: 'Microsoft Windows'
    language: 'Matlab 64-Bit'
     authors: [1x7 struct]



Yes, I also think that the problem with Hi-DPI was only on windows 8, because now I never get any errors related to that. I think that the matlab crashes are now due to another problem (or many!).


I still have many warnings and bug with beamposition.


When matlab crashes, it says acces violation, and :

This error was detected while a MEX-file was running. If the MEX-file

is not an official MathWorks function, please examine its source code

for errors.



I really hope I will be able to find solutions soon.



Thank you



Emmanuelle


________________________________
De : Mario Kleiner <notifications@github.com>
Envoyé : 22 septembre 2015 13:10
À : Psychtoolbox-3/Psychtoolbox-3
Cc : Emmanuelle Renauld
Objet : Re: [Psychtoolbox-3] Matlab crashes due to driver. (#275)


I meant the output when you executed PsychTweak('ScreenVerbosity', 4); first. But i just ran that on a Windows-7 system here with Matlab R2014a, so i probably already know what it will do.

Windows 8.1 and 10 is very different in HiDPI display handling from older Windows versions like Vista, 7 and 8, that's why Windows 8.1 would have been interesting.

But anyway, am i right that you don't get problems related to the HiDPI display on your Windows-7? Thinking about it, i would expect that those problems are solved because PTB will disable the DWM on Windows-7, so it can't screw up due to HiDPI displays. It should probably be only a problem on Windows-8 and later, where PTB can't disable the DWM, so HiDPI displays will trigger additional complications.

The sync trouble you showed above for AMD is very likely caused by the hybrid graphics. But the Intel results look good to me. Maybe the Matlab crash is caused by yet another graphics driver bug in the Intel drivers.

-

**Comment by kleinerm** [comment]
The problems with HiDPI are expected to start with Windows-8. On earlier versions PTB can disable the DWM and solve the problem that way. Matlab adds HiDPI support with its latest release R2015b, so that may be the only one we could maybe get working on HiDPI with Windows-8 or later, although that's not yet clear. The best thing to do is to stick to Windows-7 or better switch to Linux completely.
