### ISSUE TITLE
[Feature request] Screen flip on event feature

### ISSUE THREAD

**Issue by suxpert** [Psychtoolbox-3/Psychtoolbox-3#278]
Hi there,

It seems that now PTB window can flip only if Screen('flip') command is called, thus after this function call, or timeout, PTB window will display the contents.

So now, if I need the screen flip after I press a key, or click somewhere, I'll have to check again and again on keyboard status, when meet the certain event, I call the Screen('flip') command to fresh the window. ---So there are few time between the event and this flip, this delay might up to perhaps more than 2 times of monitor refresh interval.

I think, if there is such a feature, that the screen can itself listen to those events, and do the flip as soon as the event took place, it will be much better on time control.

**Comment by dcnieho** [comment]
If its very important that flip happens at the first possible moment after
the key is pressed, you should rewrite your code to make it such. PTB is a
low level toolbox, giving you full control and thereby full responsibility.

What are you doing that 2 refresh intervals might elapse between the key
being pressed and the flip occuring?

**Comment by suxpert** [comment]
Because I have to check the keyboard status again and again in a loop, and it can return only if the check returned, at that moment, key press event has already happen for a while, perhaps already missed the best time. You know, every matlab call will cost some time.

Here is a demo code snippet.
```matlab
while true
    [isd, secs, kc] = KbCheck;
    if isd && ( kc(key1) || kc(key2) || etc. )
        % remember something
        break;
    end
    WaitSecs(0.005);
end

vbl = Screen('Flip');
```

**Comment by kleinerm** [comment]
Not going to happen. Just use tic and toc, or GetSecs to measure how long your while loop takes and you'll see that is insignificant. Or use the KbQueue functions with KbEventGet to wait for key input cfe. KbQueueDemo.

Apart from that, if you use a regular keyboard it will usually have latencies and timing uncertainties in the range of dozens of milliseconds, so big that any software delay you describe will simply not matter, compared to the unavoidable error introduced by your keyboard.

**Comment by suxpert** [comment]
You know, each matlab call will cost some time, I've tried about tic/toc and GetSecs, the result may differ at some milliseconds.

In the previous loop of waiting for a key, the returned keydown time and the time I got outside the loop can differ at around 10ms, so there **are** chances that the best time is missing.

For keyboard latency, if the keyboard delay can not be avoid so there are no actual precise timing, why there are so many `time precise` related settings in psychtoolbox?

**Comment by kleinerm** [comment]
Yes, and your calls cost less than 10 microseconds, so this is pointless. The 10 msecs are from you keyboard, not from your code. The keyboard is only checked every 8 msecs by the computer, and the electronics of the keyboard itself often only checks every 20 - 50 msecs.

There are timing precision related settings because timing precision matters a lot for many experimental paradigms, not only for keyboards. There do exist gamer keyboards that are faster afaik. There do exist special keyboard for neuroscience which claim that they can respond within a millisecond or two, they are just much more expensive than normal keyboards. There exists special gaming mice, response button boxes etc. which have much better timing than keyboards.
