### ISSUE TITLE
Check if data file exists on tracker before opening it

### ISSUE THREAD

**Issue by grero** [Psychtoolbox-3/Psychtoolbox-3#280]
Hi,
 We have been having some problems where researchers have lost data files because they have inadvertently asked Eyelink to open a data file with a file name that already exists, using the EyeLink('OpenFile',fname) command. I noticed that there is a file_exist function in the Eyelink API that will be allow one to check if a file exists before opening it. Would it be possible to incorporate this function into the the OpenFile code, so that an error is thrown if the file already exists?

**Comment by kleinerm** [comment]
int file_exists (char∗path) - Checks if file and/or path exists.
Returns: 0 if does not exist, 1 if exists, -1 if cannot overwrite.

We could that as optional behavior, e.g., an extra flag to the function 'dontOpenExisting', which would throw an error if the file existed. But the default behavior has to stay the same, otherwise we'd break existing scripts of users.

**Comment by grero** [comment]
I'm completely onboard with that. Something like 'dontOpenExisting' would be great to have.

**Comment by kleinerm** [comment]
Consider it done. Not tested due to lack of Eyelink, but implemented for the next PTB beta release.

**Comment by kleinerm** [comment]
Out in current PTB BETA, so a UpdatePsychtoolbox should give you a new option for this.
