### ISSUE TITLE
DisplaySize on Linux does not give the correct answer

### ISSUE THREAD

**Issue by suxpert** [Psychtoolbox-3/Psychtoolbox-3#283]
Although in the document, it has been claimed that the result may be incorrect, I post this issue because it CAN got the right value, while it didn't.

Here is what I got on Linux:
```matlab
>> [w, h] = Screen('DisplaySize', 0)
w = 361
h = 203
>> system('xrandr')
% Screen 0: minimum 8 x 8, current 1366 x 768, maximum 32767 x 32767
% eDP1 connected primary 1366x768+0+0 (normal left inverted right x axis y axis) 310mm x 174mm
%     1366x768            60.0*+
%     ........
%     ........
```

While on windows, DisplaySize got the correct size, 310mm x 174mm, that is the same as measured.

**Comment by kleinerm** [comment]
'DisplaySize' on Linux would report the size for the X-Screen, which will always be wrong for multi-display setups with multiple displays per X-Screen. One would need to extend 'DisplaySize' to get the per-output information that you showed - the output of xrandr for eDP1. So that's more of a feature request for future work. A very low priority feature request, because the value of this is very limited due to the info not being very trustworthy.

But that doesn't change the fact that DisplaySize is unreliable on many displays on all operating systems. I've seen Windows, OSX and Linux falling over and reporting wrong results with different displays, due to driver bugs, awkward display configurations, or more often than not faulty EDID data reported by the displays themselves, because the display manufacturer did a bad job. so the doc is perfectly right to say you shouldn't trust it.

**Comment by kleinerm** [comment]
Because i was working on Screen('ConfigureDisplay", 'Scanout', screen, output) anyway, i added per-output reporting of display size to the struct returned by that function. This reports the same sizes as xrandr. But my comments still apply that reporting of display size in mm is quite often not very trustworthy on any operating system, so it is not that clear of how much value this reporting is at all.
This will be part of the next PTB beta.
