### ISSUE TITLE
Problem with multi-display mode for running real experiment

### ISSUE THREAD

**Issue by JulianaGurgel** [Psychtoolbox-3/Psychtoolbox-3#290]
Hello!

I am trying to run an experiment on MATLAB using Eyelink 1000 Plus. I'm able to calibrate and run the trial, but when the real experiment begins the Psychtoolbox shutsdown and the message below appears. 
I'm working on MATLAB in a Windows 7 PC using two screens.

Do you think you could help me?

Thank you in advance!

--------------------------------------------------------------------------------------------
PTB-INFO: Support for fast OffscreenWindows enabled.
Running experiment on a 'EYELINK CL 5.01  ' tracker.
PTB-INFO: Will disable DWM because a regular fullscreen onscreen window is opened -> We want best timing and performance.
PTB-INFO: The detected endline of the vertical blank interval is equal or lower than the startline. This indicates
PTB-INFO: that i couldn't detect the duration of the vertical blank interval and won't be able to correct timestamps
PTB-INFO: for it. This will introduce a very small and constant offset (typically << 1 msec). Read 'help BeampositionQueries'
PTB-INFO: for how to correct this, should you really require that last few microseconds of precision.
PTB-INFO: Btw. this can also mean that your systems beamposition queries are slightly broken. It may help timing precision to
PTB-INFO: enable the beamposition workaround, as explained in 'help ConserveVRAMSettings', section 'kPsychUseBeampositionQueryWorkaround'.

PTB-INFO: OpenGL-Renderer is Intel :: Intel(R) HD Graphics :: 3.3.0 - Build 8.15.10.2696
PTB-INFO: VBL startline = 900 , VBL Endline = 900
PTB-INFO: Measured monitor refresh interval from beamposition = 16.671539 ms [59.982463 Hz].
PTB-INFO: Will use beamposition query for accurate Flip time stamping.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.666451 ms [60.000777 Hz]. (50 valid samples taken, stddev=0.079037 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.666667 ms [60.000000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-WARNING: ==============================================================================================================
PTB-WARNING: WINDOWS SYSTEM IS RUNNING IN MULTI-DISPLAY MODE! ALL FLIP STIMULUS ONSET TIMESTAMPS WILL BE LIKELY UNRELIABLE!
PTB-WARNING: STIMULUS ONSET TIMING WILL BE UNRELIABLE AS WELL, AND GRAPHICS PERFORMANCE MAY BE SEVERELY REDUCED!
PTB-WARNING: DO NOT USE MULTI-DISPLAY MODE FOR RUNNING REAL EXPERIMENT SESSIONS WITH ANY REQUIREMENTS FOR ACCURATE TIMING!
PTB-WARNING: ==============================================================================================================
PTB-INFO: Support for fast OffscreenWindows enabled.

PTB-ERROR: Screen('Flip'); beamposition timestamping computed an *impossible stimulus onset value* of 13339.617245 secs, which would indicate that
PTB-ERROR: stimulus onset happened *before* it was actually requested! (Earliest theoretically possible 13339.619709 secs).

PTB-ERROR: Some more diagnostic values (only for experts): rawTimestamp = 13339.633856, scanline = 896
PTB-ERROR: Some more diagnostic values (only for experts): line_pre_swaprequest = 103, line_post_swaprequest = 873, time_post_swaprequest = 13339.633447
PTB-ERROR: Some more diagnostic values (only for experts): preflip_vblcount = 0, preflip_vbltimestamp = -1.000000
PTB-ERROR: Some more diagnostic values (only for experts): postflip_vblcount = 0, postflip_vbltimestamp = -1.000000, vbltimestampquery_retrycount = 0

PTB-ERROR: This error can be due to either of the following causes (No way to discriminate):
PTB-ERROR: Either something is broken in your systems beamposition timestamping. I've disabled high precision
PTB-ERROR: timestamping for now. Returned timestamps will be less robust and accurate, but if that was the culprit it should be fixed.

PTB-ERROR: An equally likely cause would be that Synchronization of stimulus onset (buffer swap) to the
PTB-ERROR: vertical blank interval VBL is not working properly.
PTB-ERROR: Please run the script PerceptualVBLSyncTest to check this. With non-working sync to VBL, all stimulus timing
PTB-ERROR: becomes quite futile. Also read 'help SyncTrouble' !

**Comment by kleinerm** [comment]
Hi,

it wouldn't shut down for this reason? It warns you that visual timing and timestamping is pretty broken on your setup, something that is expected on MS-Windows multi-display setups, which is why it gives that big warning about not using such a setup for timing sensitive experiments.

A dual display setup with visual stimulation on only one of the displays often works, as long as you don't interact with the Matlab GUI or other parts of the Windows GUI on the other display in any way. No keyboard input to Matlab or other apps, no mouse clicks into Matlab or any bits of the GUI etc. As soon as you do that, visual timing will be broken and not suitable for experiments, stimuli may become visually corrupted due to tearing artifacts etc. There are various other unfixable reasons for this happening on a multi-display setup.

Intel graphics cards on Windows are often especially buggy, and you have a Intel graphics card.

That's why we strongly recommend switching to Linux as operating system for work that requires robust timing etc. As far as i know all the Eyelink eyetrackers are also supported on Linux. If you can't do that then possible workarounds are running your system with only one display active - the stimulus display monitor, upgrading or downgrading to different versions of the Intel graphics driver for your machine, and generally just hoping you get lucky.

-Mario

**Comment by AmDeh** [comment]
Hi, I have a problem in windows 7, I want to show two images in screen and one of images is a plot which is updating, but the problem is the plot which was converted to images will not be shown, the following warning is showing:PTB-ERROR: Screen('Flip'); beamposition timestamping computed an *impossible stimulus onset value* of 13025.295485 secs, which would indicate that
PTB-ERROR: stimulus onset happened *before* it was actually requested! (Earliest theoretically possible 13025.298162 secs).

PTB-ERROR: Some more diagnostic values (only for experts): rawTimestamp = 13025.302650, scanline = 322
PTB-ERROR: Some more diagnostic values (only for experts): line_pre_swaprequest = 112, line_post_swaprequest = 118, time_post_swaprequest = 13025.298291
PTB-ERROR: Some more diagnostic values (only for experts): preflip_vblcount = 0, preflip_vbltimestamp = -1.000000
PTB-ERROR: Some more diagnostic values (only for experts): postflip_vblcount = 0, postflip_vbltimestamp = -1.000000, vbltimestampquery_retrycount = 0

PTB-ERROR: This error can be due to either of the following causes (No way to discriminate):
PTB-ERROR: Either something is broken in your systems beamposition timestamping. I've disabled high precision
PTB-ERROR: timestamping for now. Returned timestamps will be less robust and accurate, but if that was the culprit it should be fixed.

PTB-ERROR: An equally likely cause would be that Synchronization of stimulus onset (buffer swap) to the
PTB-ERROR: vertical blank interval VBL is not working properly.
PTB-ERROR: Please run the script PerceptualVBLSyncTest to check this. With non-working sync to VBL, all stimulus timing
PTB-ERROR: becomes quite futile. Also read 'help SyncTrouble' !

can any one help me?

**Comment by dcnieho** [comment]
Please post to the mailing list, not to a closed github question. Also, you
do not really provide any information. the psychtoolbox website has good
info about how to ask questions.

Best,
Dee
