### ISSUE TITLE
Download failure

### ISSUE THREAD

**Issue by rufus2015** [Psychtoolbox-3/Psychtoolbox-3#306]
Multiple attempts to load Psychtoolbox using DownloadPsychtoolbox.m have failed immediately following the file Psychtoolbox\PsychHardware\BitsPlusToolbox\BitsPlusTests\colorPlusTest.jpg with the errors  svn: E175009: The XML response contains invalid XML and svn: E130003: Malformed XML: no element found.  colorPlusTest.jpg downloads correctly.

I note that three other reports of identical failures have been made without receiving useful assistance or comment.

I am using Windows 8.1 64-bit, downloading Psychtoolbox-3 after installing Slik-Subversion=1.9.3-x64.msi.

In view of the number of reported failures related to initial downloads and lack of response, would you treat this condition as a valid bug report and investigate a remedy, please.

**Comment by kleinerm** [comment]
No, because this is just a temporary download failure due to some temporary problem at GitHub. That's why our instructions tell you to retry after a while. If it were a persistent problem it wouldn't be something we could fix, but only GitHub. But it isn't, otherwise we'd get many more problem reports every day. If it persists for you then something is miconfigured on your network or machine.
