### ISSUE TITLE
Business model

### ISSUE THREAD

**Issue by ghost** [Psychtoolbox-3/Psychtoolbox-3#307]
For the long-term sustainability of the Psychtoolbox, why not selling binaries (the mex files) while still providing the source code for free?

It's a common business model for free software. With a subscription system, like Red Hat does.

If some developers start providing a clone like CentOS does for RHEL, then you would need to offer more services (like support) and a stable version.

**Comment by dcnieho** [comment]
Assuming any tax issues do not get too complicated (Mario, is it possible to have a one man company in germany, where you basically pay income tax over your profits? That would probably also give you VAT deduction etc for business hardware and the like). I see this as a way where we can charge your work to our grants. Yes we could compile it ourselves or someone could make it available, but the point is that this provides a simple legal vehicle by which Mario could get paid. See it as a disguised donation. In terms of distribution nothing has to change except that a notice is added that usage of the binaries is not allowed before paying a fee (is that compatible with the license of the PTB distribution? its certainly not changing the open _source_ character of PTB in my opinion).

Cheers,
Dee

**Comment by hyiltiz** [comment]
@dcnieho, the main license of Psychtoolbox is MIT-based license, which could not restrict usage of the software by any means (this is not exact terms, of course). Therefore, even though we distribute *as is* so that you could still use *without* paying a fee, adding a term that explicitly says so is restricting users. However, we could take the binaires out of the Psychtoolbox distribution, and then require payment to get them. I imagine people would still simply compile the binaries themselves (or use 3rd-party maintained ones), but, as you noticed, it is enough to act as a legal vehicle to include in grants.
