### ISSUE TITLE
Psychtoolbox "Function Reference" webpage down (http://docs.psychtoolbox.org/)

### ISSUE THREAD

**Issue by brittyazel** [Psychtoolbox-3/Psychtoolbox-3#350]
I thought I would report that http://docs.psychtoolbox.org/ is currently down, and has been down for the past week (since we first started checking).

We are just learning how to use Psychtoolbox, and would love to be able to make use of this feature for our learning. Thanks for your help!

**Comment by qazwsxal** [comment]
Getting the same issue here, unfortunately. Anyone know of a mirror?

**Comment by kleinerm** [comment]
It's known. The server which hosts the docs page, and which is part of the Brainard lab, is moving somewhere else on their campus and is shut down until they get their new lab location set up properly. I don't know when it will come up again, and they actually want to retire that machine, which might make the whole docs page go away for quite a while.

"help Psychtoolbox" provides the same overview, and from there the various "help commandname" stuff. Not as nicely formatted and hyperlinked, but the same information.

**Comment by fangfufu** [comment]
I am happy to host the docs. If anyone can send me an archive.

**Comment by kleinerm** [comment]
See this forum message for an update and a link to the Internet Wayback machine:
https://groups.yahoo.com/neo/groups/PSYCHTOOLBOX/conversations/messages/20737

**Comment by fangfufu** [comment]
I don't mind installing WikkaWakkaWiki on my server. @kleinerm, do you know if anyone has the database for the wiki? Or should I email UPenn?

**Comment by kleinerm** [comment]
Afaik it only exists on that server - and hopefully on some kind of backup. @DavidBrainard would be the person to ask and coordinate with.

The docs also need to get update from time to time, something that has been neglected for months. The PTB Github distro has a Python script for that. It parses all M-Files for updated help texts, and runs Matlab on OSX i think to call the mex files to extract their subfunction help, although the type of Matlab/OS/mex file could be changed in that script. Then it compiles markdown for WikkaWakka and uploads it to the server.

**Comment by fangfufu** [comment]
Okay, I don't have time to figuring out how that Python update script works this in the next few days. I literally started looking into the PTB today. 

@DavidBrainard, I am happy to give you an account to my server, if you want to knock yourself out. I think for the next few days, I probably only have time to restore the database on my server.

**Comment by DavidBrainard** [comment]
We do have things backed up.  Right now we are buried from moving the lab across campus, but when we have a moment we can get them and think about how to manage.  I think the best solution would be to set things up so the docs get loaded to the github site for the project, rather than have another server to deal with.  The old wiki, we don't really need.  The counter would be nice, I'm not sure where that should go.  Maybe an AWS micro instance or some such.

**Comment by kleinerm** [comment]
Github would be ideal, but we can't do that, because GitHub doesn't support WikkaWakkaWiki and converting the docs to a Github compatible format would be quite a bit of work for somebody with the needed Markdown and scripting skills, as far as i understood Tobias comments from the past.

**Comment by dcnieho** [comment]
Well, matlab help only works if you know what a function is called. I do a
lot of support where i simply answer, "did you know of function xxx, or
demo yyy?". That said, not sure if having a google-able function reference
helps much in that, given that people probably don't know what to search
for.

Cheers,
Dee

**Comment by kleinerm** [comment]
According to the multiple bug reports on GitHub and on the PTB forum within less than 6 hours of the docs going offline, yes. I think beginners use it a lot. I also got that feedback in the past about people liking the online docs. Clicking hyperlinks is a more simple way to discover things than typing Matlab commands for many. And they are visually less cluttered.

**Comment by DavidBrainard** [comment]
I understand in principle why it might be nice to have the online docs.  I am just not sure whether anyone ever used them.  If not, it is not worth any effort to find a way to get them up again.

Best,

David

**Comment by denispelli** [comment]
dear david
i use the psychtoolbox web pages a lot. MATLAB Help has a very weak search
engine which finds only what you already know the exact name of. Google
"Psychtoolbox xxx" is smart and finds any relevant web page. I use it a
lot, and I imagine others do too.
best
denis


[image: photo]
*Denis Pelli*
Professor of Psychology & Neural Science, New York University
+1-646-258-7524 | denis.pelli@nyu.edu | http://psych.nyu.edu/pelli/ | Skype:
denispelli <#> | http://denispelli.com
<http://www.facebook.com/denispelli>

**Comment by fangfufu** [comment]
@DavidBrainard, new students tend to use it a lot...

**Comment by priyamdas** [comment]
@DavidBrainard I definitely use the docs a lot because, as mentioned, google really helps to find the relevant page. I know I'm not the only person that uses google to help debug/solve my programming problems so it'd be a great help to have the docs back online.

**Comment by jessekaye** [comment]
@DavidBrainard I second the previous comments that more novice PTB users (myself included) google the PTB function library that you host on your sever frequently when programming/debugging. No rush, but would certainly appreciate it if the website comes back up after your lab migration! Thanks

**Comment by DavidBrainard** [comment]
We will try to get the docs back up!

But it may take a month or so, as we are still recovering from time lost to moving the lab across campus.  And we may need to call in some help from the community as we didn’t set up the system, we were just hosting it on some of our hardware.

Best,

David

**Comment by DavidBrainard** [comment]
We brought the server back up.  But it is really limping along.  We don't know where the code is that processes the header files and produces the online documentation.  And the wiki that serves that documentation is no longer developed and the person who installed it has long since left the lab.

I think the right solution is for someone to update that code so that it can run locally over a copy of the PTB and produce the html, and then push the html up to the PTB gh-pages site or its wiki pages. This would get it off our current server and into a maintainable state, with the documentation served nicely off of a gitHub supported site.  We do have examples of how to push pages up to both a gh-pages or a gitHub wike site from inside of Matlab, that part is not so hard.  It is mostly a question of someone finding and updating the code that generates the HTML.

The old PTB-3 wiki itself is broken due to some configuration or OS compatibility issue with the wakka wiki.  I don't think that is coming back.  There was a nice history of the PTB page there that I wouldn't mind recovering somehow, but the juice may not be worth the squeeze.

We could probably move the download counter to an AWS or similar micro instance at some point.

Volunteers?

Best,

David
