### ISSUE TITLE
Download Problem!

### ISSUE THREAD

**Issue by Threadman** [Psychtoolbox-3/Psychtoolbox-3#374]
Hi,

While I am downloading Psychtoolbox through Matlab, I faced the same error mentioned in this issue https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/220. I didn't no how to solve as even that issue is closed without any comments.
Hope someone can help.

Regards,

**Comment by afgenovese** [comment]
Hi,

I faced the same issue, the github path, when inserted manually, gives a 404 NOT FOUND when looking for the repository

**Comment by afgenovese** [comment]
Nevermind, I restarted MATLAB and it worked

**Comment by Threadman** [comment]
I did restart Matlab but had the same error!

**Comment by kleinerm** [comment]
That issue you mentioned is either a temporary download failure due to GitHub's servers having trouble, or some issue with your local network or firewall. Retrying after a while might help. Other than that there isn't anything we could do.

You can download zip files with the latest releases from here though:
https://github.com/Psychtoolbox-3/Psychtoolbox-3/releases
And then use SetupPsychtoolbox from within the downloaded Psychtoolbox folder to manually set it up.
Obviously you won't get updates via UpdatePsychtoolbox then. And the download includes all the source code, so is hundreds of MB instead of only a few dozen.
