### ISSUE TITLE
Connect to multiple sound cards

### ISSUE THREAD

**Issue by codles** [Psychtoolbox-3/Psychtoolbox-3#383]
Is it possible to use multiple ASIO sound cards simultaneously using PsychPortAudio?

I would like to present stimuli via one RME and record via another. However, when I try to create two pahandles the system complains that I have tried to open a device multiple times. Reading or writing independently works perfectly.

Here is how I tried to open the devices...
```julia
InitializePsychSound

readDeviceID = 52;;
writeDeviceID = 53;

pahandleWrite = PsychPortAudio('Open', writeDeviceID , 1, 1, 48000, 1, [], [], [5]);      % open device and write to analog 6
pahandleRead  = PsychPortAudio('Open', readDeviceID ,  1, 0, 48000, 2, [], [], [2, 3]);   % open device and read from channels 3 and 4
```
which gives the error
```bash
PTB-ERROR: Failed to open audio device 53. PortAudio reports this error: Device unavailable 
PTB-ERROR: Could not open audio device, most likely because it is already in use by a previous call to
PTB-ERROR: PsychPortAudio('Open', ...). You can open each audio device only once per session. If you need
PTB-ERROR: multiple independent devices simulated on one physical audio device, look into use of audio
PTB-ERROR: slave devices. See help for this by typing 'PsychPortAudio OpenSlave?'.
Error in function Open: 	Usage error
Audio device unavailable. Most likely tried to open device multiple times.
```

Any help on how to get this working would be appreciated. Or if its not possible that would be great to know too.

**Comment by kleinerm** [comment]
No. It's a limitation of the underlying PortAudio engine ASIO backend - or mostly of ASIO's design itself which makes it difficult to do that.

Linux would be capable of operating multiple physical sound cards this way, and apparently many RME sound cards are well supported - according to a little Google search, i don't have any practical test experience with RME cards.

Why can't you use one card for simultaneous playback and recording?

**Comment by codles** [comment]
Thanks for the info. Its just for practical (boring) reasons that I can't use one card for playback and recording.

Appreciate your help!

**Comment by kleinerm** [comment]
Why? The driver allows full duplex operation, doesn't the card allow that?

**Comment by codles** [comment]
The speakers and mics I want to use are currently on different sound cards. I would have to change all the cables in the lab, but there are existing experiments going on, so this isn't possible for now. Thanks for the help :)

**Comment by kleinerm** [comment]
Linux would likely be a solution, and the recommended os anyway.
If you don't need precise timing or low latency or fine controlled channel routing you could also open one of the soundcards as its DirectSound or MME device instead of ASIO. Timing/latency/control awful, but maybe a way to work around the limitation. Only ASIO has that 1 soundcard per session problem.

**Comment by kleinerm** [comment]
Oh and btw. in your above example your read handle is configured for playback, not capture due to the mode parameter 1 instead of 2. Given that you specify latencyclass 0 aka no timing precision, high latency ok, there, that could be a candidate for opening via DirectSound or MME. Often channel-pairs of such a card are exposed as separate DS or MME cards iirc.
