### ISSUE TITLE
PTB initial warning when screen resolution is changed

### ISSUE THREAD

**Issue by NicolasClairis** [Psychtoolbox-3/Psychtoolbox-3#408]
Working on a very big screen (resolution: 2500x1600) on a windows computer, we changed the resolution to 1920x1200 on the windows manager. Since then, the Psychtoolbox initial warning starts appearing everytime I launch my script while it does not when the resolution of the screen is the native one. Of course in both cases the c;lassical error message about PTB synchronization failure does appear but it does not seem to relate to the screen resolution difference.

My script starts with this:
screenNumber = 0;
[L, H] = Screen('WindowSize',screenNumber );
Screen('Preference','VisualDebugLevel', 1); % avoid initial Psychtoolbox window
Screen('Preference', 'SkipSyncTests', 0);
Until today, I always thought that the warning from PTB only appears when SkipSyncTests is set to 1 to indicate that perfect synchronization is not managed.

I tried to add
Screen('Resolution',L,H)
just after the windowsize to force PTB to adapt the resolution to the one used in windows (the values in L and H were 1920 and 1200 indeed) but that didn't change anything.

I don't understand why there is this bug when resolution changes and how I could fix it or at least stop the warning from displaying given that for any subject doing my task that would appear as extremely strange to have this initial warning everytime the script is launched.

Thanks in advance for any advice on the matter.
Nicolas

**Comment by kleinerm** [comment]
I don't know which warning you mean? Output?

**Comment by NicolasClairis** [comment]
Sorry if I was not clear, I meant this
![ptb_warning](https://cloud.githubusercontent.com/assets/15351232/24585831/cf50aa1a-1793-11e7-9f69-1fc4b2da51c5.png)

**Comment by kleinerm** [comment]
That just tells you that something visual timing related went badly wrong, so what is the textual warning output in the Matlab console that goes along with the warning sign?

**Comment by NicolasClairis** [comment]
This is the warning when the resolution is changed to 1920*1200
![warning_output_ptb_1920x1200](https://cloud.githubusercontent.com/assets/15351232/24610417/bc023398-187e-11e7-966f-db545caa68cf.png)

**Comment by NicolasClairis** [comment]
And this is when the native resolution of 2500*1600 is left.
![warning_output_ptb_2500x1600_native](https://cloud.githubusercontent.com/assets/15351232/24610463/eceb7a00-187e-11e7-8889-1f1e06e3fb4b.png)

I don't understand why changing the resolution of the screen induces a synchronization failure so any advice is more than welcome.

**Comment by kleinerm** [comment]
The reason is explained in "help BeampositionQueries", which you were supposed to read, as Psychtoolbox warning output told you clearly. Non-Native digital panel resolutions often don't work with reliable timing on MS-Windows or Apple MacOSX due to operating system limitations, and the panels themselves can also introduce big timing artifacts.

The solution is to use Psychtoolbox panel fitter as demonstrated in PanelFitterDemo to leave the resolution of your panel at its native maximum resolution and let PTB generate a framebuffer with a different smaller resolution of your choice that then gets upscaled to and displayed at native panel resolution by PTB itself.

Btw. Your PTB is very outdated and unsupported in case of further problems or questions, updating to the latest v3.0.14 is recommended.
