### ISSUE TITLE
'GetImage' problem

### ISSUE THREAD

**Issue by andrisecker** [Psychtoolbox-3/Psychtoolbox-3#412]
The test function here:
https://github.com/Psychtoolbox-3/Psychtoolbox-3/wiki/FAQ:-Screenshots-or-Recordings
saves a full black image for me...
Do you have any idea what to do?

**Comment by qx1147** [comment]
This might be a graphics card/driver problem.
Instead of reading from the "frontbuffer" (the video buffer that is currently displayed) you should try reading from the "backbuffer", i.e. before flipping, like:

`   ...`
`   Screen('FillOval', wPtr, white, ovalSpecs );`
`   Screen('DrawingFinished', wPtr, [], 1);`
`   imageArray = Screen('GetImage', wPtr, [0 0 300 300],'backBuffer');`
`   Screen(wPtr, 'Flip');`
`   ...`

The 'DrawingFinished' call is supposed to make sure that the graphics card has fully processed the drawing commands before reading the image data from the backbuffer. Calling 'DrawingFinished' and even with the 'sync' flag being set, is just playing it safe (and is a bit slower); you might actually get away without setting the 'sync' flag or even without calling 'DrawingFinished' at all.

**Comment by kleinerm** [comment]
Yes. Those example code on our Wiki FAQ section you referenced is wrong. Don't know who wrote it, but whoever definitely didn't test it.

**Comment by kleinerm** [comment]
Actually, i just realized that sample code is correct. I just overlooked the 'Flip' calls because they weren't on their own lines. Fixed that. So yes, this must be a graphics driver bug on your machine. Closing...
