### ISSUE TITLE
ERROR: Failed to lookup the font from the font number

### ISSUE THREAD

**Issue by zhangyy985** [Psychtoolbox-3/Psychtoolbox-3#452]
INTERNAL PSYCHTOOLBOX ERROR
	error:                PsychError_internal
	general description:  Unspecified error, probably a Psychtoolbox bug
	specific description: Failed to lookup the font from the font number!
	module name:          Screen
	subfunction call:     TextBounds
	file name:            Common/Screen/SCREENDrawText.c
	function name:        PsychGetCTStyleAttributesFromPsychWindowRecord
	line number:          157
Error using Screen
See error message printed above.

Error in DrawFormattedText (line 302)
blankbounds = Screen('TextBounds', win, 'X', [], [], 1, righttoleft);
------------
How to solve this problem?

**Comment by kleinerm** [comment]
Not at all if you don't provide more info like hardware, OS and version, PTB version, an example script that shows the error, etc.

**Comment by zhangyy985** [comment]
Thank you for your reply. My os is 'MacOS Sierra 10.12.6', with PTB 3.0.14.

**Comment by kleinerm** [comment]
This uses the old unsupported legacy osx text renderer. It shouldn't by default, and PTB should have output warnings about this and advised you to follow the instructions in "help DrawTextPlugin" to fix it.

Other than switching to the supported renderer, you could use the macOS FontBook application and try to "Repair fonts" or however that is called, because maybe your OS font database is somehow corrupted.

**Comment by zhangyy985** [comment]
Thank you so much for your help. The problem have solved. I following the instructions in "help DrawTextPlugin", remove a file named 'libfreetype.6.3.16.dylib'. Thank you~~~

**Comment by kleinerm** [comment]
Good. Closing.
