### ISSUE TITLE
Strange blocking after TransformTexture in certain cirumstances

### ISSUE THREAD

**Issue by thht** [Psychtoolbox-3/Psychtoolbox-3#458]
Hello!

Under certain circumstances, calling `Screen('TransformTexture')` blocks Matlab execution **after** it has already returned.

I have uploaded some code, demonstrating the problem here: https://pastebin.com/FA8686jJ

As it well may be that it is an issue of my hardware/software setup, here are my specs:

1. Tested with equal behavior on Matlab 2016b and 2017b running on Debian Stretch
2. NVIDIA Quadro K2000 video card with latest proprietary drivers.

This problem does not become obvious if one only transforms a handful of textures as the blocking introduced by an individual call to `Screen('TransformTexture')` is very small. Yet, it becomes highly problematic when trying to process a movie in realtime.

I played around with the code and made the following observations:

1. The problem is only present for low texture sizes. Anything over 600x600 does not show this behavior.
2. The problem scales with the amount of calls to `Screen('TransformTexture')`. On my machine doing it 200 times leads to ~2s of blocking. Doing the same thing 500 times results in ~5s seconds of blocking.
3. The problem also scales with the size of shader kernel.
4. Waiting for an appropriate time using `WaitSecs` after the texture transforms makes the problem go away.

I am happy to provide further information or tests if needed.

Thanks a lot for this really good toolbox!

**Comment by dcnieho** [comment]
So if i understand you correctly, your problem is that the drawcalls take
longer after Screen('TransformTexture')? I suppose this simply means that
the operation is performed lazily, i.e., only executed when the result is
required. Mario will know the details here of course.

Perhaps all you need is the textureShader input of
Screen('DrawTexture', windowPointer, texturePointer [,sourceRect]
[,destinationRect] [,rotationAngle] [, filterMode] [, globalAlpha] [,
modulateColor] [, textureShader] [, specialFlags] [, auxParameters]);

I've had good success using that for pretty large realtime images.

All the best,
Dee

**Comment by thht** [comment]
Hi Dee,

thanks for the quick reply and the pointer to `Screen('DrawTexture')`. I will give it a try...

However, concerning the behavior I described cannot be explained by what you wrote, as far as I'm concerned:

1. *Any* Matlab call might take longer after `Screen('TransformTexture')`. Which one it is remains mostly stable as long as the same Matlab release is used. I had cases in which the call to fprintf (line 58) was blocking. Other cases involved the `Screen('Flip')` command.
2. If this problem is the result of a lazy operation, why does the `WaitSecs` call in 55 help?
3. As I wrote, the problem seems to be absent with large images. It seems to be present only for small ones.

Best,
Thomas

**Comment by kleinerm** [comment]
TransformTexture, like other functions that execute on the gpu, will run the actual operation in parallel on the gpu, so the time Screen('TransformTexture') returns is not when the operation finished, only when the job was submitted to the graphics driver. The gfx driver itself may be multi-threaded internally, so it could be that it returns when the driver submitted all commands to the gpu, or even earlier when it just accepted the commands and does command submission in the background.

It could be that the first command that blocks is actually one that wants to draw to the screen. 'Flip' is a natural one, as it can't flip before a stimulus is drawn, and it can't draw a blurred texture before all of them have been transformed. A fprintf() could be a candidate because it tries to draw new text to the Matlab window, which involves the gpu, so if the gpu is busy transforming textures it may not be able to accept new commands for drawing text glyphs onto the display. A WaitSecs would just voluntarily block Matlab's execution long enough to hide the processing.

NVidia gpu's also have multiple command channels, so they can in principle switch between multiple rendering clients, e.g., the Matlab fprintf / X-Server rendering, and PTB's direct rendering, to simulate multi-tasking by time-multiplexing. But how those channels are allocated is dependent on the driver. Maybe the NVidia driver changes part of the processing strategy for larger textures, or uses a different method of uploading the data or managing its memory at certain thresholds. In the end this is all so driver dependent, one can't know, especially not with a proprietary driver. E.g., do you notice the rest of the desktop GUI freezing (other windows, a digital clocks seconds display etc.) while the gpu is too busy serving such drawing requests? If i run your script on my old slow Intel gpu from 2010 then the whole GUI freezes for over 1.5 minutes.

Do the blurred textures actually look right? That kernel is rather large, so this is very compute intense. We also have Add2DSeparableConvolutionToGLOperator() to do 2-pass convolution with separable kernels, as that is more efficient for large kernels or images.

For real-time processing of a movie during playback you wouldn't transform 200 textures in one go though, but only one per getframe -> transform -> draw -> flip cycle, so you might be better off.

**Comment by thht** [comment]
hi mario,

thanks. your post is incredibly helpful!

it is actually the case that the whole GUI freezes during the background texture processing time. but only if some "drawing" action should be performed (like fprintf or some ptb screen flip...).

i have dug a bit deeper and found that if i replace the statement on line 27 with this:

```
raw_textures{idx_n} = Screen('MakeTexture', win_handle, RandLim(texture_resolution, 0, 1), 0, 0, 2);
```

i.e., i directly use 32bit floating point precision per component, the processing speed is highly increased. the reason for this might be that the gl_operator uses 16/32bit floating point precision so the texture would need to be converted somewhere in the pipeline, which seems to consume a lot of resources.

unfortunately, it does not seem to be possible to directly influence the type of the components when loading a movie. there are some options (like pixelFormat) but that did not solve the problem.

> For real-time processing of a movie during playback you wouldn't transform 200 textures in one go though, but only one per getframe -> transform -> draw -> flip cycle, so you might be better off.

yes, this is actually what i want to do and did in my implementation of the script i want to run. however, the framerate drops dramatically and the whole thing becomes essentially unusable. doing it in a loop here was just a way to isolate and demonstrate the problem.

> Do the blurred textures actually look right? That kernel is rather large, so this is very compute intense. We also have Add2DSeparableConvolutionToGLOperator() to do 2-pass convolution with separable kernels, as that is more efficient for large kernels or images.

well, of course the kernel size is a bit exaggerated in the example. however, we need to get the image really blurry, and i have not yet been able to come up with parameters for a gaussian blur that provides this kind of blurring we need that works with a lower kernel size.

i have tried using `Add2DSeparableConvolutionToGLOperator` and it helps a bit, indeed. on my system, the maximum kernel size i can use with that one is 17, while the non-separable one works only fine up until a kernel size of 7 or 9...

of course, if you have another suggestion on how to blur my movies, i am all ears :-)

best,
thomas

**Comment by dcnieho** [comment]
Hi Thomas,

Precompute blurry movies and just play those from file?

All the best,
Dee

**Comment by thht** [comment]
hi dee,

sure, this is my backup option. but i would be much more flexible if that could be done on the fly...

best,
thomas

**Comment by thht** [comment]
ok, i was able to find some more optimizations. reducing processing to 16bits by inserting

```
Screen('HookFunction', gauss_blur, 'ImagingMode', mor(kPsychNeed16BPCFloat, Screen('HookFunction', gauss_blur, 'ImagingMode')));
```

helped a lot if it is called before the call to `Add2D...`.

**Comment by kleinerm** [comment]
I don't think you need floating point processing at all for regular 8 bpc movie input. But what happens is that Add2DConvolution... requests 32 bpc float processing because it thinks the created kernel has sum(sum(kernel)) > 1. Now that should not be true for a fspecial('gaussian') kernel, but looking at it, i get:
sum(sum(kernel)) == 1.000000000000001554312234475219

iow. you are a victim of some tiny numeric error. If you do a kernel = single(kernel); before passing the kernel then the whole pipeline will work with standard 8 bit textures, requiring less gpu memory and resources.

If you only apply isotropic filtering for blurring, i think you can also pass the kPsychAssumeTextureNormalized specialflag to 'TransformTexture'. That will skip internal expensive normalizations.

If you look how warpedtex is used in ImageWarpingDemo.m to recycle one texture over and over as a container for the output of 'TransformTexture', that's another way to skip some processing overhead.

We also have some demos for live blurring of movies or video that use image resolution pyramids, e.g., BlurredMipmapDemo. That was more meant for fast gaze contingent image manipulation - simulating the difference between foveated and peripheral vision. Maybe that's of help if high speed and lots of blurryness matters.

A very efficient way of filtering via FFT in frequency space used to be GPUFFTMoviePlaybackDemo, which uses CUDA 5.0 and the FOSS GPUmat toolbox (help PsychGPGPU). However, i don't know if CUDA 5 is still well supported by current NVidia gpu's and drivers, and the GPUmat toolbox seems to be unmaintained since multiple years. This was to my knowledge only used by very few users, so i haven't tested it in years.

**Comment by thht** [comment]
hi mario,

i actually tried to normalize the kernel in my code. and you are right that `Add2DConvolutionToGLOperator` does include this check. however, i turned to using `Add2DSeparableConvolutionToGLOperator` now as you suggested and because it results in a significant performance boost. however, that function includes these lines:

```
if bitand(Screen('HookFunction', gloperator, 'ImagingMode'), mor(kPsychNeed16BPCFloat, kPsychNeed32BPCFloat)) == 0
    % Not yet set. Choose highest precision:
    Screen('HookFunction', gloperator, 'ImagingMode', mor(kPsychNeed32BPCFloat, Screen('HookFunction', gloperator, 'ImagingMode')));
    if debug > 3
        fprintf('Add2DSeparableConvolutionToGLOperator: Increasing precision of operator to 32bpc float.\n');
    end
end
```

if i understand this if-clause correctly, it checks whether 16 or 32bit floating point precision is used. if this is not the case, it automatically enables 32bit fp precision. the only way i found to prevent this from happening is by setting the shader's precision to 16bit before calling `Add2DSeparableConvolutionToGLOperator`. but maybe, even 16bit is not needed here? in that case, it might make sense to tweak the function itself?

**Comment by kleinerm** [comment]
You can try if removing that in your own custom variant helps speed without introducing artifacts and inaccuracy. Separate convolution is a two-pass process, so intermediate results from pass 1, used as input to pass 2, need to be stored. If you choose regular 8 bit fixed-point storage, intermediate results will get rounded/truncated down to less than 3 digits behind the decimal point, whereas in the single-pass convolution all calcs happen at ~6-7 digits precision and only the end result is rounded back to 8 bit.

So you might lose a bit of precision in the blurring, if that matters, and maybe a slight speed gain.
The other mentioned optimizations should still be applicable to the separable convolution.
