### ISSUE TITLE
Support for iOS MATLAB Mobile

### ISSUE THREAD

**Issue by gregguvic** [Psychtoolbox-3/Psychtoolbox-3#459]
MATLAB has come out with a very handy iOS app, but it cannot run ptb commands. I doubt an iPhone would have the capacity to run ptb, but I would hope at least the iPad Pro could handle it. Support for the iPad app would be extremely useful to run MATLAB experiments made with ptb on the go.

**Comment by kleinerm** [comment]
I shudder on the thought of dragging more people into Apples buggy operating-system eco-system. macOS is disastrous enough for reproducible research, i really wouldn't want to deal with iOS. Also iOS != macOS, so PTB for macOS couldn't run on iOS in the first place.

But apart from that, that IOS app is just a remote client for a Matlab instance running on a regular PC or Mac, as far as i understand. PTB can't run on a remote machine and then present on the iPad.

So this is a no-go for various reasons.

**Comment by kleinerm** [comment]
Btw., what might work if you need a tablet, is using a windows tablet / tablet-pc / two-in-one. If you run it under Windows with a suitable Matlab or Octave, you can use PTB for Windows, however probably with not great visual or auditory stimulation timing, as Intel onboard gfx/sound in such tablets usually has pretty deficient drivers under Windows. And touch input would only be via GetMouse mouse emulation.

If you get a tablet that allows installation of Linux, you can run PTB for Linux with likely very good visual/auditory timing due to much better drivers. Also full multi-touch input from the touchscreen. However, finding a suitable tablet and Linux installation might be a bit of a challenge.
