### ISSUE TITLE
PsychJava causes segfaults in C++ mex files 

### ISSUE THREAD

**Issue by Yonisher** [Psychtoolbox-3/Psychtoolbox-3#495]
I have a mex file written in C++ that uses mexMakeMemoryPersistent, which stops working when the PsychJava is included in the matlab path - attempting to access memory that has been made persistent results in a segfault. I can provide my C++ code if necessary, but it's a driver for a particular piece of hardware so it's not reproducible on other setups.

**Comment by kleinerm** [comment]
What happens if you remove/rename the function PsychJavaSwingCleanup.m ?

I can not think of any way PTB's Java could cause this, unless you are hitting some Matlab bug or such. But PsychJavaSwingCleanup.m contains a windowing system workaround for other Matlab+Java bugs that would otherwise trigger Java.lang.outofMemory errors after running a visual stimulation script a few times.

**Comment by Yonisher** [comment]
Interesting - I will try it. 
So far what works is removing everything I'm not using from the path. I am pretty sure some matlab memory function is being shadowed, but I haven't yet figured out which one.
