### ISSUE TITLE
OpenHMD - Vive Pro - Linux - Psychtoolbox fails to find second screen and updates to openhmdkeepalivedaemon

### ISSUE THREAD

**Issue by rennis250** [Psychtoolbox-3/Psychtoolbox-3#527]
Hello,

yesterday, we tried to use Psychtoolbox's OpenHMD support on Linux (Ubuntu 18.04 LTS), and got all the way to having our HTC Vive Pro recognized by Psychtoolbox, but the device is not recognized as a second screen. This is fine for now because we have enabled an extended desktop and can either open a full-screen window that covers our monitor and the Vive Pro display, or we can open a windowed draw area that covers the Vive Pro only. However, it would be best if Psychtoolbox recognized the Vive Pro as a true separate display. Here are the steps we followed to get to this point:

0. Fully update the system and install latest Nvidia drivers, preferably a version greater than 387.12 (in our case, version 390), in accordance with the recommendations here:

https://github.com/ValveSoftware/SteamVR-for-Linux

1. Install Psychtoolbox using the older DownloadPsychtoolbox.m script. Using the NeuroDebian repositories leads to PsychOpenHMDVRCore.mex64 not being found by MATLAB, even though it is in the same directory as Screen.mex64, for reasons that I could not determine.

2. Install OpenHMD and HIDAPI from the github sources. OpenHMD had to be installed using the Meson/Ninja build tools for automatic creation of libopenhmd.so. If built with CMake, one only gets a static library, libopenhmd.a by default, which doesn't work for later steps.

3. Download the openhmdkeepalivedaemon.c code from the following link:

https://github.com/kleinerm/Psychtoolbox-3/blob/master/PsychSourceGL/Cohorts/openhmdkeepalivedaemon.c

4. Edit lines 105 and 122 to check for the string "HTC Vive", since this is now what OpenHMD reports.

5. Compile openhmdkeepalivedaemon.c with the following line:

```
gcc openkeepalivedaemon.c -o openkeepalivedaemon -lm -lopenhmd
```

6. Copy the just compiled openkeepalivedaemon executable and the openkeepalive.service file (found here: https://github.com/Psychtoolbox-3/MiscStuff/tree/master/OpenHMD64BitIntelUbuntuLinux) to the locations specified at the bottom of that link (for clarity: https://github.com/Psychtoolbox-3/MiscStuff/tree/master/OpenHMD64BitIntelUbuntuLinux).

7. According to an issue on the OpenHMD Github page, when using an Nvidia card, one should try changing the "AllowHMD" setting in the X.org configuration to get the Vive Pro display recognized as a second screen. This does not interfere with position tracking or receiving signals from the controllers. The discussion can be found here:

https://github.com/OpenHMD/OpenHMD/issues/109

We made the appropriate file, which we named /etc/X11/xorg.conf.d/20-nvidia.conf, with the following contents:

```
Section "Device"
        Identifier "Nvidia Card"
        Driver "nvidia"
        VendorName "NVIDIA Corporation"
        Option "AllowHMD" "yes"
EndSection
```

8. Reboot the system and the Vive Pro is now shown as a separate display in Settings->Devices->Displays, in the Nvidia Settings panel, and in ARandR. The desktop wallpaper is shown on the Vive Pro and one can move the mouse and see it appear on the HMD. Using the following Matlab code also works and gives the correct diagnostic output from the Vive Pro:

```octave
PsychImaging('PrepareConfiguration');
PsychVRHMD('AutoSetupHMD');
```

Also, the demos from the OpenHMD repo compile and work fine, and so does the openhmdkeepalivedaemon executable. However, ```Screen('Screens')``` returns only 0.

So, the final question: any clue why the Vive Pro is recognized as a second screen by the operating system but not by Psychtoolbox?

Best,
Rob

**Comment by kleinerm** [comment]
> Hello,
> 
> yesterday, we tried to use Psychtoolbox's OpenHMD support on Linux (Ubuntu 18.04 LTS), and got all the way to having our HTC Vive Pro recognized by Psychtoolbox, but the device is not recognized as a second screen. This is fine for now because we have enabled an extended desktop and can either open a full-screen window that covers our monitor and the Vive Pro display, or we can open a windowed draw area that covers the Vive Pro only. However, it would be best if Psychtoolbox recognized the Vive Pro as a true separate display. Here are the steps we followed to get to this point:
> 

Use XOrgConfCreator to create a dual-X-Screen setup, screen 0 for the desktop GUI, screen1 for the Vive's video output. Then use XOrgConfSelector + logout/login to enable the setup. From there on the Vive should display on screen 1 and get optimal timing and performance. The neccessary "AllowHMD" setting for the NVidia driver is already included in this xorg.conf file. Oh, also make sure to delete your self-made xorg.conf then, so the right one applies.

>     1. Install Psychtoolbox using the older DownloadPsychtoolbox.m script. Using the NeuroDebian repositories leads to PsychOpenHMDVRCore.mex64 not being found by MATLAB, even though it is in the same directory as Screen.mex64, for reasons that I could not determine.
> 

That's because NeuroDebian unfortunately doesn't ship all mex files yet, only the common ones, e.g., nothing related to VR afaik.

>     2. Install OpenHMD and HIDAPI from the github sources. OpenHMD had to be installed using the Meson/Ninja build tools for automatic creation of libopenhmd.so. If built with CMake, one only gets a static library, libopenhmd.a by default, which doesn't work for later steps.

Yes, i see there's a new version of libopenhmd.so out. I'll update our prebuilt copy once i find time for that.

> 
>     3. Download the openhmdkeepalivedaemon.c code from the following link:
> 
> 
> https://github.com/kleinerm/Psychtoolbox-3/blob/master/PsychSourceGL/Cohorts/openhmdkeepalivedaemon.c
> 
>     1. Edit lines 105 and 122 to check for the string "HTC Vive", since this is now what OpenHMD reports.
> 

Is that change actually needed? I think the "Vive" string in the code should also match "HTC VIve" properly?

> 
> So, the final question: any clue why the Vive Pro is recognized as a second screen by the operating system but not by Psychtoolbox?
> 

For proper low-latency performance, timing and timestamping precision the Vive must be on a separate X-Screen, that's why XOrgConfCreator is needed for this. Operating everything from a single X-Screen will impair timing precision and performance.

**Comment by kleinerm** [comment]
I should mention that HTC Vive is so far completely untested with PTB, as i didn't have any access to suitable hardware. So quality-wise, your mileage may vary.

**Comment by rennis250** [comment]
Thank you for this information, Mario.

> Use XOrgConfCreator to create a dual-X-Screen setup, screen 0 for the desktop GUI, screen1 for the Vive's video output. Then use XOrgConfSelector + logout/login to enable the setup. From there on the Vive should display on screen 1 and get optimal timing and performance. The neccessary "AllowHMD" setting for the NVidia driver is already included in this xorg.conf file. Oh, also make sure to delete your self-made xorg.conf then, so the right one applies.

This does as you say, but after a Window is opened on the Vive screen (Screen 1), it is always black, regardless of what I draw to the screen, so we have gone back to the setup mentioned in my opening post. Curiously, that setup passes Psychtoolbox's synchronization tests, but we don't need perfect synchronization or optimal performance right now. We just want to test some basic things first.

> That's because NeuroDebian unfortunately doesn't ship all mex files yet, only the common ones, e.g., nothing related to VR afaik. 

As far as I remember, the VR mex files were installed by NeuroDebian. I will double check on a different machine, but I distinctly remember those mex files being there and being confused about why they were not being seen by MATLAB.

> Is that change actually needed? I think the "Vive" string in the code should also match "HTC VIve" properly?

To be honest, I didn't look at the details of ```strstr```. I just assumed that it was a straight comparison of two strings. I did not know that it searches for a sub-string that matches the second parameter.

Thanks,
Rob

**Comment by kleinerm** [comment]
On Mon, Jan 28, 2019 at 8:04 PM Robert J. Ennis
<notifications@github.com> wrote:
>
> Thank you for this information, Mario.
>
> Use XOrgConfCreator to create a dual-X-Screen setup, screen 0 for the desktop GUI, screen1 for the Vive's video output. Then use XOrgConfSelector + logout/login to enable the setup. From there on the Vive should display on screen 1 and get optimal timing and performance. The neccessary "AllowHMD" setting for the NVidia driver is already included in this xorg.conf file. Oh, also make sure to delete your self-made xorg.conf then, so the right one applies.
>
> This does as you say, but after a Window is opened on the Vive screen (Screen 1), it is always black, regardless of what I draw to the screen, so we have gone back to the setup mentioned in my opening post. Curiously, that setup passes Psychtoolbox's synchronization tests, but we don't need perfect synchronization or optimal performance right now. We just want to test some basic things first.
>

Hmm, this was tested with a Oculus Rift CV1 about a year ago and
worked. At that time still with Ubuntu 16.04 LTS though, as 18.04 LTS
wasn't a thing then.

Can you send the ~/.local/share/xorg/Xorg.0.log file and output of
xrandr --screen 1 ?
If you move the mouse cursor out of the screen, does it show up on the
Vive? Or is the Vive's display switched off?

> That's because NeuroDebian unfortunately doesn't ship all mex files yet, only the common ones, e.g., nothing related to VR afaik.
>
> As far as I remember, the VR mex files were installed by NeuroDebian. I will double check on a different machine, but I distinctly remember those mex files being there and being confused about why they were not being seen by MATLAB.
>

Yep. Seems the file gets installed, but the soft-links don't get
generated as they should, apparently NeuroDebian missed that.

> Is that change actually needed? I think the "Vive" string in the code should also match "HTC VIve" properly?
>
> To be honest, I didn't look at the details of strstr. I just assumed that it was a straight comparison of two strings. I did not know that it searches for a sub-string that matches the second parameter.

It's a sub-string match, so the current code should work.
-mario

**Comment by kleinerm** [comment]
No user response in months. User obviously doesn't care. Closing.

**Comment by andreagrant** [comment]
I have just gotten an HTC Vive Pro that I'm trying to get working with PTB. I was able to get the device setup using XOrgConfCreator and selector. If I open a Screen window the "normal" way (just addressing the second screen), I can draw stimulus, but if I try any of the following I get just the black "screen" on the Vive (it looks like the display is off):

- hmd = PsychOpenHMDVR('AutoSetupHMD','Monoscopic')
- VRHMDDemo
- ImagingStereoDemo(103)

Here's the info you requested

xrandr --screen 1
Screen 1: minimum 8 x 8, current 2880 x 1600, maximum 32767 x 32767
DP-0 connected primary 2880x1600+0+0 (normal left inverted right x axis y axis) 120mm x 70mm
   2880x1600     90.04*+



[Xorg.0.log](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/3698418/Xorg.0.log)

Thanks,

Andrea

**Comment by kleinerm** [comment]
On Mon, Oct 7, 2019 at 6:16 PM andreagrant <notifications@github.com> wrote:
>
> I have just gotten an HTC Vive Pro that I'm trying to get working with PTB. I was able to get the device setup using XOrgConfCreator and selector. If I open a Screen window the "normal" way (just addressing the second screen), I can draw stimulus, but if I try any of the following I get just the black "screen" on the Vive (it looks like the display is off):
>
> hmd = PsychOpenHMDVR('AutoSetupHMD','Monoscopic')

What does this command above report?

The libopenhmd.so that we provide in our Misc Git repository is too
old to support the Vive Pro. You'd need to get the latest v0.3 of
libopenhmd from GitHub, unless it is already bundled with your OS, but
i think all Ubuntu's - and thereby Popos - ship a too old v0.2
version. I don't think the display will power up with our
libopenhmd.so.

> VRHMDDemo
> ImagingStereoDemo(103)
>
> Here's the info you requested
>
> xrandr --screen 1
> Screen 1: minimum 8 x 8, current 2880 x 1600, maximum 32767 x 32767
> DP-0 connected primary 2880x1600+0+0 (normal left inverted right x axis y axis) 120mm x 70mm
> 2880x1600 90.04*+
>

The above output suggests the Vive Pro was detected by the X-Server,
and it's just the panel that stays dark due to libopenhmd.so < version
0.3.

> Xorg.0.log

This Xorg.0.log is not related to the Vive, it seems to relate to your
normal desktop setup.
-mario

**Comment by andreagrant** [comment]
This is what I see from the PsychOpenHMDVR command: 

`hmd = PsychOpenHMDVR('AutoSetupHMD','Monoscopic')
PsychOpenHMDVR: Opening the first connected OpenHMD VR headset.
PsychOpenHMDVRCore-INFO: Opened OpenHMD device with deviceIndex 0 as handle 2.
PsychOpenHMDVRCore-INFO: Product: External Device - Manufacturer: OpenHMD - Path: (none)
PsychOpenHMDVRCore-INFO: Panel size in pixels w x h = 1280 x 800
PsychOpenHMDVRCore-INFO: ----------------------------------------------------------------------------------
Warning: PsychOpenHMDVRCore: Open: metersPerTanAngleAtCenter
value unknown for this HMD, using Oculus Rift DK2 default.
Please try to find a proper setting! 
> In PsychOpenHMDVR (line 983)
  In PsychOpenHMDVR (line 880) 

hmd = 

  struct with fields:

                       handle: 2
                       driver: @PsychOpenHMDVR
                         type: 'OpenHMD'
                      subtype: 'OpenHMD'
                         open: 1
                    modelName: 'External Device'
                   panelWidth: 1280
                  panelHeight: 800
    separateEyePosesSupported: 0
              controllerTypes: 0
       VRControllersSupported: 0
        handTrackingSupported: 0
      hapticFeedbackSupported: 0
                    autoclose: 0
                   hswdismiss: 3
                 basicQuality: 0
                    basicTask: ''
            basicRequirements: ''
    metersPerTanAngleAtCenter: 0.0565`

**Comment by kleinerm** [comment]
Ja, that's wrong and shows the VivePro wasn't detected / misdetected
as some external input device. As expected if you didn't
get/compile/install the latest OpenHMD v0.3 yourself.

I will have to look into updating our own libopenhmd.so to the latest
state for user convenience, but can't say if it will be a day or days
or weeks before i get to it.
-mario

**Comment by kleinerm** [comment]
So libopenhmd.so in our Psychtoolbox-3/MiscStuff git repository is now up
to date with the latest from the OpenHMD project.
Installing this new libopenhmd.so should enable Vive Pro support.

-mario

**Comment by brunoRichard** [comment]
I must say this thread has been very informative and helpful in getting everything set-up. A big thank you for all the information. 

I am, however, encountering some issues with displaying stimuli/images in the Vive. I've gotten to the point where Psychtoolbox "recognizes" the HTC Vive (I'm not sure it does). I've created a new configuration file using XOrgConfSelector to assign Screen 0 to the desktop monitor and Screen 1 to the HTC Vive. 

When I open a new window `[win, rect] = PsychImaging('OpenWindow', screenID)` - I get this message:

> PsychOpenHMDVR-Info: Overriding onscreen window framebuffer size to 847 x 1058 pixels for use with VR-HMD direct output mode.

While it does open a window I can draw to in the HMD; it does not fill the display. Instead, the window is a section of the bottom left corner of the Vive Screen. The rest of the Vive screen is filled by whatever was previously drawn (e.g., the warning message from Psychtoolbox). When I Screen('CloseAll'), the screen(s) on the Vive go black but are still on as I can move my cursor to it (but the cursor turns into an x). 

I have the most recent version of libopenhmd.so (which I compiled from the Git Repository using meson and ninja as instructed above), the keepAlive files, and I followed the instructions from the ReadMe file in the MiscStuff folder to make sure everything is in the right directory. 

Still, there are a few oddities that lead me to believe the HTC Vive is not correctly detected. 1) I cannot run PsychOpenHMDVR without specifying the device index, as I get an error saying the OpenHMD with device index 0 could not be open. 2) The panel size in pixels doesn't seem right (1280x800) - unless I'm wrong and this doesn't refer to the display size in pixels. 3) The hmd structure returns a model name of HMD Null Device, which I assume is incorrect. I've attached the outputs of PsychOpenHMDVR and hmd below. 

> PsychImaging('PrepareConfiguration');
>> hmd = PsychOpenHMDVR('AutoSetupHMD','Monoscopic',[],[],1);
PsychOpenHMDVRCore-INFO: OpenHMD VR runtime initialized.
PsychOpenHMDVRCore-INFO: At startup there are 4 OpenHMD HMDs available.
PsychOpenHMDVRCore-INFO: Opened OpenHMD device with deviceIndex 1 as handle 1.
PsychOpenHMDVRCore-INFO: Product: HMD Null Device - Manufacturer: OpenHMD - Path: (none)
PsychOpenHMDVRCore-INFO: Panel size in pixels w x h = 1280 x 800
PsychOpenHMDVRCore-INFO: ----------------------------------------------------------------------------------
Warning: PsychOpenHMDVRCore: Open: metersPerTanAngleAtCenter value unknown for this HMD, using Oculus Rift
DK2 default. Please try to find a proper setting! 
> In PsychOpenHMDVR (line 983)
  In PsychOpenHMDVR (line 874) 

> hmd = 

  struct with fields:

                       handle: 1
                       driver: @PsychOpenHMDVR
                         type: 'OpenHMD'
                      subtype: 'OpenHMD'
                         open: 1
                    modelName: 'HMD Null Device'
                   panelWidth: 1280
                  panelHeight: 800
    separateEyePosesSupported: 0
              controllerTypes: 0
       VRControllersSupported: 0
        handTrackingSupported: 0
      hapticFeedbackSupported: 0
                    autoclose: 0
                   hswdismiss: 3
                 basicQuality: 0
                    basicTask: ''
            basicRequirements: ''
    metersPerTanAngleAtCenter: 0.0565
                          OVR: [1×1 struct]

Since this seems to be related to previous questions, I've also attached the output of xrandr --screen 1 and have attached the Xorg.o.log file (in case these are useful). 

> xrandr --screen 1
Screen 1: minimum 8 x 8, current 2160 x 1200, maximum 32767 x 32767
HDMI-0 connected primary 2160x1200+0+0 (normal left inverted right x axis y axis) 122mm x 68mm
   2160x1200     89.53*+
   720x480       59.94  
   640x480       59.93 

[Xorg.0.log](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/4156101/Xorg.0.log)

I am using the NVIDIA GeForce GTX 1060 3GB, with the HTC Vive connected into the HDMI port and the monitor connected into a display port, if this matters in any way. 

Any ideas on why the Vive is not recognized correctly and why the size of the window I open changes to a small window presented in the bottom left corner? Any assistance would be much appreciated. 

Thanks, 

Bruno

**Comment by luzhuoen123** [comment]
Hello guys, 
      
Thank you so much since I found this thread has been very informative and helpful in getting everything set-up. However, I met an issue that the MATLAB crashed when I ran the built-in VRHMDDemo1. It was a bit weird coz everything looks normal, but finally MATLAB crashed.
      
Here is the log for the terminal while running ptb3-matlab,

```
 ohnnylu@johnnylu-MS-7D42:~$ sudo ptb3-matlab
[sudo] password for johnnylu: 
Gtk-Message: 13:21:04.056: Failed to load module "canberra-gtk-module"
/usr/local/MATLAB/R2019b/bin/glnxa64/jcef_helper: symbol lookup error: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_memdup2
/usr/local/MATLAB/R2019b/bin/glnxa64/jcef_helper: symbol lookup error: /lib/x86_64-linux-gnu/libpango-1.0.so.0: undefined symbol: g_memdup2
[II] 0bb4:0309 1-3.2.1.4.1:1.0

[II] opening

[II] 28de:2300 1-3.2.1.3:1.0

[II] opening

[II] 28de:2300 1-3.2.1.3:1.1

[II] 28de:2300 1-3.2.1.3:1.2

[II] manufacturer: 'HTC'

[II] product: 'VIVE Pro'

[II] serial number: '207937574756'

[II] power on magic: 64

[II] Enable Pro IMU magic: 64

[II] Getting feature report 16 to 39

got -1 bytes
[WW] Could not read config. Using defaults.

[WW] Could not get range packet.

[EE] gyro error: -0.022449, 0.052462, -0.050265

libptbdrawtext_ftgl: External 'DrawText' text rendering plugin initialized.
libptbdrawtext_ftgl: Maximum number of cacheable fonts is 40, minimum number of supported concurrent windows is 10.
libptbdrawtext_ftgl: This plugin uses multiple excellent free software libraries to do its work:
libptbdrawtext_ftgl: OGLFT (http://oglft.sourceforge.net/) the OpenGL-FreeType library.
libptbdrawtext_ftgl: The FreeType-2 (http://freetype.sourceforge.net/) library.
libptbdrawtext_ftgl: The FontConfig (http://www.fontconfig.org) library.
libptbdrawtext_ftgl: Thanks!

GameMode ERROR: Could not connect to bus: /usr/bin/dbus-launch terminated abnormally with the following error: EOF in dbus-launch reading address from bus daemon

dbus[4889]: arguments to dbus_connection_unref() were incorrect, assertion "connection != NULL" failed in file ../../../dbus/dbus-connection.c line 2822.
This is normally a bug in some application using the D-Bus library.

  D-Bus not built with -rdynamic so unable to print a backtrace
Segmentation fault (core dumped)
```

Also here is the MATLAB crash report,

```
--------------------------------------------------------------------------------
               abort() detected at Wed Jan 25 13:15:44 2023 +0000
--------------------------------------------------------------------------------

Configuration:
  Crash Decoding           : Disabled - No sandbox or build area path
  Crash Mode               : continue (default)
  Default Encoding         : UTF-8
  Deployed                 : false
  Desktop Environment      : ubuntu:GNOME
  GNU C Library            : 2.35 stable
  Graphics Driver          : Unknown hardware 
  Graphics card 1          : 0x10de ( 0x10de ) 0x2487 Version 525.85.5.0 (0-0-0)
  Java Version             : Java 1.8.0_202-b08 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  MATLAB Architecture      : glnxa64
  MATLAB Entitlement ID    : 1563295
  MATLAB Root              : /usr/local/MATLAB/R2019b
  MATLAB Version           : 9.7.0.1737446 (R2019b) Update 9
  OpenGL                   : hardware
  Operating System         : Linux 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64
  Process ID               : 5307
  Processor ID             : x86 Family 6 Model 151 Stepping 2, GenuineIntel
  Session Key              : 265c6955-efac-4c04-b595-72d729a29618
  Static TLS mitigation    : Enabled: Full
  Window System            : The X.Org Foundation (12101003), display :1

Fault Count: 1


Abnormal termination:
abort()

Register State (from fault):
  RAX = 0000000000000000  RBX = 00007f65fffff640
  RCX = 00007f6620444a7c  RDX = 0000000000000006
  RSP = 00007f65ffffab10  RBP = 000000000000151f
  RSI = 000000000000151f  RDI = 00000000000014bb

   R8 = 00007f65ffffabe0   R9 = 0000000000000b06
  R10 = 0000000000000008  R11 = 0000000000000246
  R12 = 0000000000000006  R13 = 0000000000000016
  R14 = 0000000000000008  R15 = 00007f65ffffaeb0

  RIP = 00007f6620444a7c  EFL = 0000000000000246

   CS = 0033   FS = 0000   GS = 0000

Stack Trace (from fault):
[  0] 0x00007f6620444a7c                    /lib/x86_64-linux-gnu/libc.so.6+00617084 pthread_kill+00000300
[  1] 0x00007f66203f0476                    /lib/x86_64-linux-gnu/libc.so.6+00271478 raise+00000022
[  2] 0x00007f66203d67f3                    /lib/x86_64-linux-gnu/libc.so.6+00165875 abort+00000211
[  3] 0x00007f6489e18ed6               /lib/x86_64-linux-gnu/libdbus-1.so.3+00048854
[  4] 0x00007f6489e3f690               /lib/x86_64-linux-gnu/libdbus-1.so.3+00206480 _dbus_warn_return_if_fail+00000000
[  5] 0x00007f64c926804f             /lib/x86_64-linux-gnu/libgamemode.so.0+00012367
[  6] 0x00007f6444128b12 /usr/share/psychtoolbox-3/PsychBasic/Screen.mexa64+00125714
[  7] 0x00007f644416478d /usr/share/psychtoolbox-3/PsychBasic/Screen.mexa64+00370573
[  8] 0x00007f64441d33a0 /usr/share/psychtoolbox-3/PsychBasic/Screen.mexa64+00824224 mexFunction+00001296
[  9] 0x00007f66157dbde3     /usr/local/MATLAB/R2019b/bin/glnxa64/libmex.so+00548323
[ 10] 0x00007f66157dbee5     /usr/local/MATLAB/R2019b/bin/glnxa64/libmex.so+00548581
[ 11] 0x00007f66157dc317     /usr/local/MATLAB/R2019b/bin/glnxa64/libmex.so+00549655
[ 12] 0x00007f66157dcf93     /usr/local/MATLAB/R2019b/bin/glnxa64/libmex.so+00552851
[ 13] 0x00007f66157c87ac     /usr/local/MATLAB/R2019b/bin/glnxa64/libmex.so+00468908
[ 14] 0x00007f6617bad15f /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_dispatcher.so+01073503 _ZN8Mfh_file20dispatch_file_commonEMS_FviPP11mxArray_tagiS2_EiS2_iS2_+00000207
[ 15] 0x00007f6617baec5e /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_dispatcher.so+01080414
[ 16] 0x00007f6617baf1a1 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_dispatcher.so+01081761 _ZN8Mfh_file8dispatchEiPSt10unique_ptrI11mxArray_tagN6matrix6detail17mxDestroy_deleterEEiPPS1_+00000033
[ 17] 0x00007f660a48da63 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+14006883
[ 18] 0x00007f660a492816 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+14026774
[ 19] 0x00007f660a59983e /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+15104062
[ 20] 0x00007f660a58cb91 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+15051665
[ 21] 0x00007f660a4f97b4 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+14448564
[ 22] 0x00007f660a51fdcd /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+14605773
[ 23] 0x00007f6609ca32db /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+05706459
[ 24] 0x00007f6609ca5514 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+05715220
[ 25] 0x00007f6609ca22bd /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+05702333
[ 26] 0x00007f6609c8f791 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+05625745
[ 27] 0x00007f6609c8f9c9 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+05626313
[ 28] 0x00007f6609ca1ac6 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+05700294
[ 29] 0x00007f6609ca1bc6 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+05700550
[ 30] 0x00007f6609ddb6e9 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+06985449
[ 31] 0x00007f6609ddee23 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+06999587
[ 32] 0x00007f660a349891 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+12679313
[ 33] 0x00007f660a2f8063 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+12345443
[ 34] 0x00007f660a2fc0af /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+12361903
[ 35] 0x00007f660a2ff0e2 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+12374242
[ 36] 0x00007f660a39872f /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+13002543
[ 37] 0x00007f660a398a19 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwm_lxe.so+13003289
[ 38] 0x00007f66198914c4 /usr/local/MATLAB/R2019b/bin/glnxa64/libmwbridge.so+00341188 _Z8mnParserv+00000596
[ 39] 0x00007f6617f675b5   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwmcr.so+01017269
[ 40] 0x00007f662163d42b   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwmvm.so+03097643 _ZN14cmddistributor15PackagedTaskIIP10invokeFuncIN7mwboost8functionIFvvEEEEENS2_10shared_ptrINS2_13unique_futureIDTclfp_EEEEEERKT_+00000059
[ 41] 0x00007f662163d518   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwmvm.so+03097880 _ZNSt17_Function_handlerIFN7mwboost3anyEvEZN14cmddistributor15PackagedTaskIIP10createFuncINS0_8functionIFvvEEEEESt8functionIS2_ET_EUlvE_E9_M_invokeERKSt9_Any_data+00000024
[ 42] 0x00007f661847689c   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwiqm.so+00751772 _ZN7mwboost6detail8function21function_obj_invoker0ISt8functionIFNS_3anyEvEES4_E6invokeERNS1_15function_bufferE+00000028
[ 43] 0x00007f6618476557   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwiqm.so+00750935 _ZN3iqm18PackagedTaskPlugin7executeEP15inWorkSpace_tag+00000439
[ 44] 0x00007f6617f56015   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwmcr.so+00946197
[ 45] 0x00007f661845b6a0   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwiqm.so+00640672
[ 46] 0x00007f661843fe01   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwiqm.so+00527873
[ 47] 0x00007f6618440a7f   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwiqm.so+00531071
[ 48] 0x00007f6617f3d575   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwmcr.so+00845173
[ 49] 0x00007f6617f3db93   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwmcr.so+00846739
[ 50] 0x00007f6617f3e404   /usr/local/MATLAB/R2019b/bin/glnxa64/libmwmcr.so+00848900
[ 51] 0x00007f661fc13bdd /usr/local/MATLAB/R2019b/bin/glnxa64/libmwboost_thread.so.1.65.1+00080861
[ 52] 0x00007f6620442b43                    /lib/x86_64-linux-gnu/libc.so.6+00609091
[ 53] 0x00007f66204d4a00                    /lib/x86_64-linux-gnu/libc.so.6+01206784
[ 54] 0x0000000000000000                                   <unknown-module>+00000000

    
This error was detected while a MEX-file was running. If the MEX-file
is not an official MathWorks function, please examine its source code
for errors. Please consult the External Interfaces Guide for information
on debugging MEX-files.
```
        
I am not sure if the issue was due to the Ubuntu itself since I am using the latest 22.04 LTS (I tried to use different versions of MATLAB but all crashed). Maybe I should use an older one like 18.04 or 20.04 LTS? I also got latest nvidia driver, PTB, OpenHMD, as well as correct XScreen setting for the Vive Pro. I am using NVIDIA Geforce RTX 3060 with the HTC Vive Pro connected via DP, with two monitors connected via HDMI and DP.
          
Anyone could give me suggesstion about how to fix this issue? Thank you so much!
      
Best,
Johnny

**Comment by rennis250** [comment]
What happens if you use the Nouveau (open-source Nvidia drivers)?

If that also fails, then yes, a test with 20.04 LTS and testing both Nvidia and Nouveau drivers on there could be worth it. If that does not fix it, then something odd might be going on with OpenHMD.

- Rob

**Comment by kleinerm** [comment]
This issue is closed, it was already closed before @luzhuoen123 posted. They continued in this forum thread...
https://psychtoolbox.discourse.group/t/htc-vive-pro-linux-matlab-crashed-when-i-ran-vrhmddemo1/4800/4
...where they got offered free advice that resolved that issue - not free to us ofc., my work time costs us money, then ran into another problem, got offered paid support, and then were too cheap to pay a mere 99 Euros to get their problem solved. I guess their work is so unimportant that it is just not worth 99 Euros. Or they think not supporting us is the best way to keep Psychtoolbox alive and well, because I can totally pay my rent and food with thank you notes.
