### ISSUE TITLE
Problems with XOrgCreator and XOrgSelector

### ISSUE THREAD

**Issue by rmabreu** [Psychtoolbox-3/Psychtoolbox-3#537]
Hello! I am running PTB-3 on Linux (Ubuntu 18.04.2 LTS) under MATLAB R2018b. I have two display monitors, and I would like to use one of them for debugging, and the other one to test the stimuli that I am coding.

I have run the PsychLinuxConfiguration.m script as suggested in the tutorial, as well as the XOrgConfCreator.m and XOrgConfSelector.m scripts. I have tried multiple combinations of different answers to the questions prompted by the last two scripts, and the closest that I got was one monitor always back with a white "x" symbol (unless my stimuli is running), and the functioning normally.

Could you please help me on this? Thanks!

**Comment by kleinerm** [comment]
What graphics card? Open-source graphics drivers (Mesa)? I'd need to see all the output of the XOrgconfCreator and how you answered. "diary on" in Matlab will log all this to a diary.txt file.

**Comment by rmabreu** [comment]
Thank you for your reply. Here's the output of the XOrgConfCreator:

Detecting type of primary display graphics card (GPU) and driver to use...
Nvidia GPU with proprietary driver detected. Primary display gpu type: nvidia
Uses the xf86-video-nvidia DDX video driver.
Found a total of 2 video output displays on 1 X-Screens.

Multiple displays (active video outputs) detected.

Do you want a single X-Screen (s) or a dual/multi X-Screen (m) setup? [s / m] m

The following outputs are available for assignment to X-Screen 0:

1) Output HDMI-0.
2) Output DVI-D-0.

Please enter the numbers of the outputs which should be assigned to X-Screen 0.
These will be the display outputs used to display the GUI with Octave and Matlab.
Enter space-separated list of numbers of outputs to use, RETURN to finish: 2

There are 1 unassigned active video outputs left.
Do you want to create another X-Screen for some of these? [y/n] n

Will create 1 X-Screens with the following output assignment:
X-Screen 0: DVI-D-0
Do you want to configure special/advanced settings? [y/n] n

Ready to write the config file. I propose this filename and location:
/home/rodolfo/.Psychtoolbox/XorgConfs/90-ptbconfig_1_xscreens_1_outputs_nvidia.conf
Type ENTER/RETURN to accept, or provide an alternative filename: 

We are done. Now you can run XOrgConfSelector any time to select this configuration
file to setup your system, or to switch back to the default setup of your system. Bye!

**Comment by kleinerm** [comment]
When it asks: "There are 1 unassigned active video outputs left.
Do you want to create another X-Screen for some of these? [y/n] n"

You should answer 'y'es, not 'n'o, so it lets you assign the HDMI-0 output to a new X-Screen 1 aka PTB screen 1 for your visual stimulus display.

**Comment by rmabreu** [comment]
When I answer yes, the HDMI-0 output will always be a black screen with the "x" white symbol for the mouse, except when displaying the visual stimulus. Ideally, I would like to have this HDMI-0 output available as well while not displaying any stimulus. Is that possible?

**Comment by kleinerm** [comment]
Ah, now i understand what you meant with the X. That is expected behaviour and shows it is working :)

Nope, that's not possible atm. In dual-x-screen mode, the 2nd screen is only usable by PTB for fullscreen stimulation - or other applications that know how to use X-Screens > 0. By default, regular GUI desktops like KDE, Gnome, Ubuntu desktop, etc. only use X-Screen 0 for the GUI.

Or to be more specific, it is possible to setup your desktop environment to also run an instance of the desktop on X-Screen 1 (e.g., export DISPLAY=:0.1; applicationtorun) but this is DE and distribution specific, so you'd have to do your own internet research on how to achieve that on your setup. Also the system treats the separate X-Screens as separate, e.g., you couldn't drag an application window from one screen to the other.

You can use XOrgConfSelector (with config 0) + logout/login though to switch between regular desktop mode and PTB data collection mode.

**Comment by rmabreu** [comment]
Oh I see - well at least it is working according to what is expected :) I am not an expert on sys admin related tasks, so I believe that my best option is to use XOrgConfSelector and switch between the .conf files, as you suggested.

Thank you very much for your time, and for clarifying this for me.

**Comment by kleinerm** [comment]
Yes. It is a bit cumbersome to have to do this switch and logout/login dance, but that's because this mode of operation is used by almost no one except neuroscientists and a few other niche applications that need high performance timing. On the plus side: More accurate and trustworthy visual stimulation timing and control than on any other operating system :) - so in the end, it is a small price to pay.
