### ISSUE TITLE
Matlab crashing when loading specific movie file. 

### ISSUE THREAD

**Issue by ksasmita** [Psychtoolbox-3/Psychtoolbox-3#546]
Hi, 

Background: I'm trying play multiple short movie clips successively. 

Machine os: Windows 7
Matlab: 2018b
PTB version: 3.0.15
Gstreamer version: 1.0

Issue: Matlab crashes when trying to load 1 particular video file **if** it follows another video file. The problematic video file is shorter (~24seconds) than the other video files (1 min). 

Crash report attached here:
[matlab_crash_dump.pdf](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/3065605/matlab_crash_dump.pdf)

I think it originated when psychtoolbox is trying to open the movie, i.e on line: 
Screen('OpenMovie', ...) 

Elaboration on crash occurrences: 
1. Matlab crashes when problematic video is played after another video (when played in the middle of the video sequence or at the very end). 
2. Matlab did not crash when problematic video is played first or alone. 
3. I have tried replacing the video (i.e. deleting said file, saving a new mov file and replacing it to the folder) - matlab still crashes following the same problem above. 

What worked so far: 
1. Lengthening the duration of the video - it worked fine when video length (cut from the same source and saved in the same format) is 47 seconds in duration. 

Could it be that there is a minimum video length for movie display in psychtoolbox? It'll be great if I can get some advice on this issue. 

Thanks for your help! 

p.s. the same set of files and script worked perfectly fine on my macbook.

**Comment by kleinerm** [comment]
No idea. Psychtoolbox doesn't have any minimum limit of movie duration, and has been tested with clips as short as 1 second. The crash seems to happen inside a GStreamer owned processing thread, which would hint at some bug specific to GStreamer for MS-Windows, possibly with a specific codec, if this doesn't happen on macOS.

The more surprising thing is that GStreamer works for you at all under R2018b, unless you are running this in matlab.exe -nojvm mode? Most people experience crashes of Matlab otherwise, but the crash dump suggests this is not such a crash following the typical pattern.

Are you using GStreamer 1.14.4 as recommended?

So i don't know. Maybe also try with matlab -nojvm mode or Octave-4.4.1 (must use GStreamer 1.14.4 and follow Octave specific setup, as explained in the "Windows" section of this announcement:
[http://psychtoolbox.org/PTB-3.0.15-Released.html](http://psychtoolbox.org/PTB-3.0.15-Released.html)

This to rule out any bad interactions with Matlab.

Other than that, what movie format do you use? Maybe encode in a different format, if the bug is codec specific?

**Comment by kleinerm** [comment]
No response by user for over a month. Closing.
