### ISSUE TITLE
moaldemo fails on octave

### ISSUE THREAD

**Issue by eflister** [Psychtoolbox-3/Psychtoolbox-3#548]
just cuz neither the local .wav's nor handel exist.

**Comment by eflister** [comment]
also, what is the magic number in `alGetSourcef(source, AL.SAMPLE_OFFSET)/16384`?  i notice it is 2^14 and it looks like a sampling rate that happened to come from one of the possibly loaded audio files, but shouldn't it be queried with `alGetBufferi(buffers, AL_FREQUENCY)` in case a different file was chosen or moal resampled it?  is the problem that none of the `alGetBuffer*` are implemented yet?

`PsychSound/Contents.m` (from 12 years ago) says:
```
% Some OpenAL functions are not yet implemented in the toolbox, because
% these functions can't get automatically generated, so their wrappers need
% to be coded manually. Our goal is to provide full support for the
% OpenAL-API but finalizing all functions may take some time. Mostly some
% of the query-functions - functions that don't set OpenAL state or execute
% some operation, but query the current settings of OpenAL, are missing.
% Also, some of the more exotic OpenAL extensions are not yet supported.
%
% Apart from these limitations that will get removed in the future,
```
how hard would it be to manually finish the query functions?  i could volunteer to do it if instructed on how to do so.  :)

the moal demos say they are `trash code for initial testing and development. Better demos will follow soon.` i'm just looking at moal for the first time so wondering what things i should look out for that the examples are neglecting?

**Comment by kleinerm** [comment]
I made some improvements in my repo https://github.com/kleinerm/Psychtoolbox-3/commits/master on July 14th/15th, which will be part of the next PTB beta. Thanks for offering to do it, but i found some other problems that crept up on Matlab R2015b+ and also want to get a new release out soon, so i did it myself. If you want to know how to manually add new functions, those commits of the last two days should serve as reference. Atm. there are various extensions provided by OpenAL-Soft, which are not implemented. Most of them are probably irrelevant for our use cases though. In general few people seem to use the 3D sound support, given nobody noticed it was broken on all Matlab releases since R2015b, or that moaldemo was broken on Octave.

The magic number is fixed now and should have been freq - leftovers from some hacking.
As you noted, i didn't pay much love to the OpenAL support. Mostly due to little user demand and also my  disappointment with how poorly spatialization at least with headphones and for my head works. The underwhelming experience didn't create the desire in me to spend much more time on fancy demos or tweaking.

While looking at the code i did realize though that at least OpenAL-Soft, which is the default implementation shipping on Linux distributions like Debian and Ubuntu, does now implement advanced stuff like proper HRTF loading and rendering, with the ability to use one's own custom HRTF's if one is so lucky to have some. At least the default average HRTF that comes with OpenAL-Soft doesn't work that splendidly for me. But then i also only have shitty headphones, and i didn't play much with the new shiny implementation. The lack of head tracking is another limiting factor for reducing back/front confusion etc., which nowadays one could probably get for cheap by wearing a VR headset with head tracking.
