### ISSUE TITLE
Download old versions web documentation unclear

### ISSUE THREAD

**Issue by Moo-Marc** [Psychtoolbox-3/Psychtoolbox-3#564]
Seems the web info http://psychtoolbox.org/versions about downloading older versions is missing the required revision numbers for these versions.  Or here: http://psychtoolbox.org/download#archived, it says to give e.g. 'Psychtoolbox-3.0.12' as the fourth argument, but there is no fourth argument to the download function.
Giving it as the third argument, I get: "Syntax error in revision argument 'Psychtoolbox-3.0.12'"
or same thing with just '3.0.12'.
Can you clarify how to get these versions?
(P.S. I eventually got them from Github, but the documentation should be clarified.)
Cheers

**Comment by kleinerm** [comment]
Indeed, since 7 years it is no longer the 4th argument to DownloadPsychtoolbox, but the 2nd argument! Fixed, thanks for reporting. The "help DownloadPsychtoolbox" was right, but the website out of date.

Wrt. revision numbers. Those old versions are not revisions, but maintained as separate branches, whose name you give as the 2nd argument. This allows to still make changes to old versions/branches if needed, although this is very rarely done, e.g., if a critical bug is found immediately after branching off.
