### ISSUE TITLE
 KbQueueStart and GetChar 

### ISSUE THREAD

**Issue by KhaledAbdellatif** [Psychtoolbox-3/Psychtoolbox-3#580]
hi all, 

thanks for the nice toolbox. 
I was runningn the: Example 1 - shows key-response times from visual onset
but for some reason the KbQueueStart function wont work. 
error: 
Keyboard queue for device NaN already in use by GetChar() et al. Use of GetChar and keyboard
queues is mutually exclusive!
I just dont know how to disable the Getchar function or not let it reserve my keybouard. 
any suggesions? 
greetings, 
Khaled

**Comment by kleinerm** [comment]
I don't know what "Example 1" is? Not a part of Psychtoolbox, maybe from some outside tutorial?

Anyway, if you used ListenChar(n) with n > 0, or CharAvail or GetChar before KbQueueCreate etc. then that won't work on all operating systems + runtime combos, e.g., not with GNU/Octave and not on MS-Windows with Matlab or Octave, because those functions also use KbQueues themselves internally. It's one or the other. A ListenChar(0) would release the KbQueue, so KbQueueCreate etc. would work again.

Either there's a bug in your example, or maybe some script you ran before used GetChar et al. and didn't release them properly? In such a case a ListenChar(0) or restarting Matlab or Octave should fix it.
