### ISSUE TITLE
Minimal alpha level in DrawTextures

### ISSUE THREAD

**Issue by matanmazor** [Psychtoolbox-3/Psychtoolbox-3#585]
Hello! 
I'm running a psychophysical experiment at near-threshold visibility, in which gratings are presented at very low levels of opacity (alpha = ~0.0045), on a gray background. I'm controlling alpha via the _DrawTextures_ function, e.g. ` Screen('DrawTextures', w, target, [], [], [], [], params.Alpha);` 
I was wondering whether there is any minimal value for alpha, such that values below it mean that nothing is printed to the screen at all. For example, the texture is based on a matrix with values ranging from 0 to 255, and alpha can be set to values lower than 1/255. Would _DrawTextures_ cope with this? 
Thanks!

**Comment by kleinerm** [comment]
On a standard 8 bpc framebuffer with standard 0-255 8 bpc textures, you'd get at most a 1 intensity unit difference at the peak of your grating, because texel value 255 * 0.0045 is rounded about 1 unit. -> Your grating wouldn't be a (sine-)grating anymore but a minimal amplitude square-wave. Probably not good enough for almost any low contrast paradigm.

Look at AdditiveBlendingForSuperPositionTutorial.m for how to enable high precision textures and framebuffers, which use a normalized 0.0 - 1.0 color range instead of 0 - 255 and operate with about 23 bits of linear precision or about six digits behind the decimal point.

Of course you still need to get such a low contrast grating actually displayed. A standard 8 bpc framebuffer and display won't cut it. AdditiveBlendingForSuperPositionTutorial('PseudoGray') demonstrates a method to emulate about 10.7 bits of grayscale precision via a technique known as "bit stealing" ie. about 2.7 bits better precision on  a well calibrated 8 bit display - up to 1768 gray levels perceived instead of 256. AdditiveBlendingForSuperPositionTutorial allows for various other high precision output methods iff your hardware is capable of doing it. E.g., via 10 bit native display panels or 10 bit simulated color precision on 8 bit panels via dithering on Linux, 11 bit simulated (dithering) on Linux with a 10 bit display and AMD gpus, 11 bit true precision with Linux + AMD gpu + native 12 bit panel, around 12 bits grayscale with old CRT monitors and a Videoswitcher, or 12, 14, or 16 bit color precision with suitable visual stimulators attached from VPixx or CRS.

**Comment by matanmazor** [comment]
Thanks kleinerm for the detailed answer, that's very helpful - I will ask in the forum next time!

**Comment by matanmazor** [comment]
Where can I find AdditiveBlendingForSuperPositionTutorial?

**Comment by kleinerm** [comment]
In PTB, but i made a typo. It's AdditiveBlendingForLinearSuperPositionTutorial.m
