### ISSUE TITLE
Error Message Downloading Psychtoolbox

### ISSUE THREAD

**Issue by samgo02** [Psychtoolbox-3/Psychtoolbox-3#593]
Hi,

I've been having some difficulty downloading Psychtoolbox-3 on one of my Lenovo laptops (Windows 10 Pro). I was able to get Matlab to function with Psychtoolbox-3 on my other computer, but I continue to get error messsages on the second one. I downloaded the new Matlab version (R2019a) as well as Psychtoolbox-3; these are the error messages that keep coming up:

"svn: E170013: Unable to connect to a repository at URL 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox' 
svn: E230001: Server SSL certificate verification failed: issuer is not trusted 
Sorry, the download command "CHECKOUT" failed with error code 1:
svn: E170013: Unable to connect to a repository at URL 'https://github.com/Psychtoolbox-3/Psychtoolbox-3/branches/beta/Psychtoolbox'
svn: E230001: Server SSL certificate verification failed: issuer is not trusted

The download failure might also be due to temporary network or server problems. You may want to try again in a few minutes. It could also be that the subversion client was not (properly) installed. On Microsoft Windows you will need to exit and restart Matlab or Octave after installation of the Subversion client. If that does not help, you will need to reboot your machine before proceeding. Another reason for download failure could be if an old working copy - a Psychtoolbox folder - still exists. In that case, it may help to manually delete that folder. Or maybe you do not have write permissions for the target folder?

Error using DownloadPsychtoolbox (line 814)
Download failed."

I've been trying to resolve this problem for the past couple of days. I've deleted everything (Gstreamer, Slik, Psychtoolbox-3) and tried starting over again, but that didn't help either. I also deleted the previous Psychtoolbox folders, but nothing seems to work. Is there anything else I should try?

Thanks in advance,
Sam

**Comment by dcnieho** [comment]
Simply download using a git clone or the download button here on github,
take only the psychtoolbox folder in there, place it where you want, and
run setuppsychtoolbox.m

**Comment by samgo02** [comment]
Sorry, I'm not super familiar with any of this software, it's my first time dealing with this issue. What exactly should I download? Thanks!

**Comment by mikelgg93** [comment]
@samgo02, if you are familiar with Git:
go to 'C:/' open the command line and type _git clone https://github.com/Psychtoolbox-3/Psychtoolbox-3.git_, then run SetupPsychtoolbox.m as @dcnieho commented to you.
otherwise...
![image](https://user-images.githubusercontent.com/11683112/65733687-20a7b200-e113-11e9-8383-24b22afa0f89.png)
Click there, to download the ZIP file, extract it on your laptop at "C: /".  Go to the folder C:/Psychtoolbox-3/Psychtoolbox/ and click on the .m file that says SetupPsychtoolbox.m
Follow the instructions.
Oh, and ensure you previously have the GStreamer installed:
https://gstreamer.freedesktop.org/data/pkg/windows/1.16.0/gstreamer-1.0-msvc-x86_64-1.16.0.msi
And the Microsoft Visual Studio Runtime 2015-2019:
https://github.com/Psychtoolbox-3/Psychtoolbox-3/raw/master/Psychtoolbox/PsychContributed/vcredist_x64_2015-2019.exe
