### ISSUE TITLE
Daq for multiple sound source project

### ISSUE THREAD

**Issue by cpw27grohlab** [Psychtoolbox-3/Psychtoolbox-3#599]
Can daq in psych toolbox be used to randomly send 8 different inputs to an given number of outputs 1-8? 

for reference: http://psychtoolbox.org/docs/Daq

**Comment by kleinerm** [comment]
I don't understand your question. Please be way more specific about what you want to do and what your hardware + OS setup is.

**Comment by cpw27grohlab** [comment]
Here is the info on my hardware/OS setup. I am using a windows 10 computer with Matlab 2018 and psychtoolbox 3.0.15. I also have a MOTU 8M audio interface that is connected to my computer in order to connect it to 8 speakers. The goal of the project is to be determine how many sound sources someone can hear at one time. To do this I am setting up an experiment with 8 speakers set up equidistant from each other over 180 degrees. I will test human subjects by sending 8 sounds to any given number of the 8 speakers: it could be any arrangement from one sound played from each speaker, to all eight sounds played through one speaker. I must create a program (using psychtoolbox in matlab, or open to suggestions of other programs/toolboxes) that will allow me to randomly send these 8 sounds (inputs) to any arrangement of outputs (speakers). The subject will then have to respond (on a computer in front of them) how many sources (speakers) they heard sounds coming from.

Please let me know if you would like me to clarify anything else, and thank you for your help in advance!

**Comment by kleinerm** [comment]
That's audio output, that you want, so DAQ is the wrong method, but our
audio driver PsychPortAudio should be excellent for such stuff. As a
starting point look at the audio demos like BasicSoundOutputDemo.m if
timing/timing-control would be of no concern at all, and more advanced
stuff wrt. timing/timing-control, and control in general, like
PsychPortAudioTimingTest.m, BasicAMAndMixScheduleDemo.m,
BasicSoundScheduleDemo.m, SimpleSoundScheduleDemo.m.

Look at the help of "PsychPortAudio Open?" to learn about how to specify
number of audio channels, ie. 8 in your case, as our demos usually only
demo 1 or 2 channel mono/stereo use.

For spatialized 3D Sound there's also our OpenAL support, e.g.,
AudioTunnel3DDemo.m, AudioTunnel3DDemo2.m. This is using OpenAL on suitable
audio hardware, the stuff one usually uses for video games etc. for
spatialized sound. Downside is no/less control over presentation timing
etc. The PsychPortAudio driver allows excellent timing/schedule control,
many audio channels etc., so for a 8 speaker setup might be more
appropriate if you want to make sure where exactly the sound comes from,
instead of just wanting 3d audio presented at the discretion of the sound
cards audio driver in a vendor specific/proprietary way.

-mario
