### ISSUE TITLE
Windows 10 window desktop manager

### ISSUE THREAD

**Issue by AlexLepauvre** [Psychtoolbox-3/Psychtoolbox-3#602]
Dear all,

we have been using Psychtoolbox 3 to run an experiment, but the computers were recently updated to windows 10. Following this update, Psychtoolbox sends a warning regarding the DWM desktop compositor being active. I did a bit of research and it appears that this issue appears with every version newer than windows 7. According to this thread: https://github.com/Psychtoolbox-3/Psychtoolbox-3/issues/276, there is no way to deal with the issue. This thread is however rather old, and I was wondering whether there is any way to deal with it? 
My understanding is that as long as the desktop manager is on, the presentation onset cannot be trusted, as the desktop manager is first processing what is to be presented on the screen before actually presenting it. This means  that there might be an extra jitter between the command and the actual presentation, is that correct? 
Finally, I have a question regarding the severity of the issue. Is it only causing one missed frame in some cases? Or is it worse? I also receive a message at the end of my experiment stating that the flip command have missed the requested stimulus presentation deadline, is this issue related?

Kind regards,

Alex

PS: I apologize in advance if my question has already been answered, or if it is not the correct place to post it.

**Comment by dcnieho** [comment]
As far as i know, Mario's reply to the opening post in that thread is still
current. We have some timing tests you can run to see if your system does
not horribly malfunction (e.g. VBLSyncTest). Barring that, you should
probably verify timing using photodiodes or such. I have not done the
latter as it doesn't matter enough in my case, but the former tests report
fine results (on some of my systems), and animation run smoothly.
As always, measure=knowing

**Comment by kleinerm** [comment]
What Diederick says.

The messages are adapted in their tone / severity, depending if it is a Vista/Win-7/Win-8.x system or a Windows-10 system, a single-display or multi-display setup, and if the OS reports the compositor enabled vs. active. It is heuristic based on testing on different setups to describe the most likely situation. As a heuristic it can be wrong if MS changes key behaviour, and there are no mechanisms to "ask" the OS what's up and get a reliable answer. The only reliable way to detect trouble is either iff PTB prints further warnings/error messages about timing, or by using things like photo-diodes masterfully - i've seen enough situations where people (including myself) fooled themselves with photo diodes or such as well, because computers are sneaky. If PTB thinks something is wrong then it almost certainly is, but if it doesn't detect any trouble then there's still the potential for more sneaky errors, only detectable by proper use of hw measurement equipment. This applies to MS-Windows and to a certain degree to macOS, depending on graphics card, and if the PsychtoolboxKernelDriver is used. On Linux our diagnostics are much better and can catch more sneaky problems in software, thanks to Linux superior builtin mechanisms for such things.

Windows 7 is still your best bet often, as we can disable the compositor with certainty and know with certainty if it is enabled/active or not. But Windows-7 is only 2 months away from its end-of-life.

Windows 10 has a compositor that behaves more friendly in many scenarios than Windows-8/8.1, but PTB has no direct means at all anymore to detect if it is interfering or not, hence the more vague info message about the possibility of DWM interference and to check with independent hardware. If you get sync failure or timing trouble reported, or timestamping errors then there's certain mayhem. If those tests pass but the noise of the measured framerate ("stddev") is high, it could be compositor mayhem or just a noisy system --> Measure with hw. If no warnings or such show up and you wan to be certain against sneaky problems --> measure with hw. There are various reasons for dwm to kick in, like HiDPI displays or mixed normal + HiDPI setups, or apps that are not DPI aware on a HiDPI setup, or wrong color depths other than 8 bpc, or multi-display setups, wrong video resolutions, user clicking on to the wrong place on the desktop GUI while stimulation is running, and various others. Errors of up to 3 video refresh cycles, e.g., 50 msecs on a 60 Hz display have been observed in practice.
As Windows-10 is not one OS anymore, but one of many editions, depending on when you installed it and on what update cycle you are, it is impossible to make any clear statements wrt. Windows-10 anymore, apart from verify if you depend on it.

Or you safe yourself all this trouble in most configurations and install Linux.

**Comment by AlexLepauvre** [comment]
Dear all,

Thanks a lot for these very helpful clarifications. 

There are two things that remain unclear to me. First of all, what exactly are we talking about when we are speaking of timing issues? Are the timestamps going to be inaccurate or are the execution of the flips not what it should be? There could indeed be three scenario: either the timestamps are inaccurate, or the execution of the flips is not what it should or both. What I would like to know is whether the timestamps are accurately reflecting the onset of the refresh rate period during which the stimulus was presented, despite the stimulus onset not being what it should be? If that is the case, this means that the issues can be monitored from the log files. But if the logged time stamps are inaccurate, or worth, if both the timestamps AND the flip execution timings are off, this would be more problematic. We are anyways considering using hw to control for it, as well as a switch to Linux.

This lead me to my second question: you mention that one should use the photo-diode skillfully, implying some non straightforward issues. The way we are intending to implement it is by having an additional box on the screen, which is drawn on the back buffer together with the stimulus and flipped upon stimulus onset. The box is presented on a corner of the screen and is highly contrasting with the color that was present on the corner before the flip. That way, we can analyze the signal of the photo-diode and synchronize the onset triggers to it. Does that seem reasonable to you, or are there some additional caveats I did not foresee?

Thanks in advance for your support.

Kind regards,

Alex
