### ISSUE TITLE
Oculus Rift screen flashes at PsychImaging

### ISSUE THREAD

**Issue by ddepireux** [Psychtoolbox-3/Psychtoolbox-3#605]
Using PTB 3.0.16 on Windows 10, Matlab R2019b and an Oculus Rift:

When the program gets to PsychImaging(), the Rift's screen flashes a very bright white screen for about .25 seconds before the rendering proper starts. Is there a simple solution? Thanks in advance. It's on the last line below:

---
global GL;  
global OVR;     
doSeparateEyeRender = 1; multiSample = 8;
PsychDefaultSetup(2);

Screen('Preference', 'SkipSyncTests', 1);
screenid = max(Screen('Screens'));
InitializeMatlabOpenGL;
PsychImaging('PrepareConfiguration');
hmd = PsychOculusVR1('AutoSetupHMD', 'Tracked3DVR', 'LowPersistence TimeWarp', 0);
[win, winRect] = PsychImaging('OpenWindow', screenid, [0 0 0], [], [],[], [], multiSample);

**Comment by kleinerm** [comment]
This seems to be due to some changes or maybe bugs in the Oculus VR runtime software provided by Oculus. I've seen the behaviour also with some apps from the Oculus store under high load. The next PTB beta release will contain some hacks to try to workaound the problem and avoid this as much as possible. They seem to help at least with the runtime as of beginning of August 2021.
