### ISSUE TITLE
which screen? mirroring?

### ISSUE THREAD

**Issue by denispelli** [Psychtoolbox-3/Psychtoolbox-3#624]
Two questions about multiple screens.
1. Under macOS, one can use System Preferences: Displays to select mirroring. Mario tells me that this gives very slow performance. Is there any way to tell through software that the user has turned on mirroring?
2. Screen allows us to use a "screen" argument to select among displays. I used to use multiple displays. Recently i've been using just the laptop built in screen. However, I have been testing a large LG screen connected to a MacBook Pro laptop. In the old days the screen with the menu bar was screen 0, and other screens were 1, etc. However, yesterday I noticed that the LG screen had the menu bar, yet was screen 1. What is the current rule for which screen is screen zero?
Best
Denis Pelli
denis.pelli@nyu.edu

p.s. 
MATLAB 2019a
latest Psychtoolbox
macOS Mojave

**Comment by kleinerm** [comment]
Already answered elsewhere. Wrt. 2-1, the same rule since day one for macOS: screen 0 is the designated main display, as it corresponds to he first entry returned by CGGetActiveDisplayList(): Docs state "The first entry in the list of active displays is the main display. In case of mirroring, the first entry is the largest drawable display or, if all are the same size, the display with the greatest pixel depth."
