### ISSUE TITLE
Infinite wait by hidden dialog from InitializePsychSound or PsychPortAudio

### ISSUE THREAD

**Issue by denispelli** [Psychtoolbox-3/Psychtoolbox-3#637]
THE PROBLEM: 
Under macOS, MATLAB requires the user's permission to use the
microphone. The user grants permission by going to
System Preferences : Security & Privacy : Privacy
and clicking the checkbox next to "MATLAB". 
https://support.apple.com/guide/mac-help/control-access-to-your-microphone-on-mac-mchla1b1e1fe/mac
Note that each time one upgrades MATLAB, the user will again have to grant
permission to the new MATLAB application. If one calls
 InitializePsychSound and PsychPortAudio while MATLAB does not yet have permission, then
either InitializePsychSound or PsychPortAudio puts up a modal dialog
asking the user to grant permission. Alas, if this comes up while we have
a full-screen window from Screen, then the dialog is displayed behind our
window and cannot be seen. MATLAB waits forever for the user to click the
invisible dialog box. As far as I can tell, the only way for the user to recover control is to
kill MATLAB. It's dismaying because there is no clue to why MATLAB hung up.
Note that giving permission to use the microphone is needed very
infrequently, once each time one upgrades MATLAB. 

PROPOSED SOLUTION:
Inside the code of InitializePsychSound of PsychPortAudio, before opening the modal dialog that requests permission, please check to see if Screen has an open window. If it does, then first call sca to close all windows and issue a warning alerting the user to what happened. Then go ahead, as usual, with opening the modal dialog. This allows the user to see the dialog and grant the needed permission. Doing just that would be great. It would be even better, if, when control returns from the modal dialog you issue a fatal error explaining that since a needed window has been closed, the user should start the program again, which should now work if the user has granted the needed permission.

What do you think?

**Comment by dcnieho** [comment]
I'd say make this part of the SetupPsychToolbox or one of the routines it
calls? Or would that trigger too infrequently possibly? If the latter, i
guess what you propose makes sense. Can you implement it?

**Comment by kleinerm** [comment]
That's not something we do. The trainwreck pops up that modal dialog, presumably when the driver opens an audio capture device, without us having any control about it, or even any feedback if or when it happens. Also, a failure - if permission isn't granted - doesn't show up in a way we could recover from or handle. I can't remember if the audio device just fails to open, or if we'd simply record eternal silence. I think similar brain-dead OS behaviour is implemented for keyboard checks and for access to the builtin camera. I think additionally in some cases Matlab just crashes if one tries to capture from the internal camera, because Matlab itself lacks some credentials and the geniuses at Apple decided that this shouldn't cause an error return from the video capture api's, but the whole process should be killed immediately.

One of many fun new bugs and misdesigns in macOS. I think some of it became even way worse in Catalina. I don't have any solution for this atm., except always run some audio capture or video capture first in non-fullscreen mode after installing Matlab. Maybe add that somewhere to some documentation - pull requests welcome.

Sometimes launching apps from the terminal helps, at least with Octave, not so much with Matlab. Apples "security design" apparently thinks that anything launched from the Terminal.App *is* the terminal app, asks for permission for the microphone etc. for Terminal.App and then grants it to almost anything launched from Terminal in perpetuity. This OS never fails to entertain.
