### ISSUE TITLE
Clear MEX crash

### ISSUE THREAD

**Issue by hannah-willis** [Psychtoolbox-3/Psychtoolbox-3#643]
Hello,

When I use the 'clear all' function after running a Psychtoolbox programme, MATLAB crashes and says that it has 'encountered an internal error and needs to close'. I have tried each of the different 'clear' functions and it seems to be the 'clear mex' aspect that is causing the problem. This occurs in 2014b (the version I was using) but also 2019a. The same code has previously worked on this computer and works perfectly fine on another Macbook pro with the same operating system (Mojave, version 10.14.6), version of MATLAB (2014b, 2019a) and version of Psychtoolbox (3.0.16). 

Do you know what might be happening? And if so, can you suggest any tips to fix it? I've attached the error message, any help would be great!
[ClearAllError.pdf](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/4171187/ClearAllError.pdf)

Thanks!

**Comment by kleinerm** [comment]
My best guess would be it has something to do with the libraries you have installed in /usr/local/lib/, e.g., /usr/local/lib/libgobject-2.0.0.dylib, /usr/local/lib/libglib-2.0.0.dylib etc. Normally GLib's are part of GStreamer, and they aren't located under /usr/local/lib. Maybe you have some conflicting software package installed that causes PTB/GStreamer/Matlab to choose the wrong GLib's from /usr/local/lib/ and then some confusion/corruption during a clear Screen -> Reload Screen cycle. Just a hunch.

**Comment by hannah-willis** [comment]
Thanks for your help! Downloading GStreamer seems to have fixed the problem. It says that it is not necessary for Mac but maybe it was corrupted somehow.

**Comment by kleinerm** [comment]
It's indeed not necessary if you don't use multi-media functions. However, and our docs might be lacking there, if you use PTB for Matlab without GStreamer, it might be that also text rendering quality/speed/flexibility is reduced, as PTB will use a fallback text renderer. Have to check that.

And the detection logic that makes GStreamer optional may get confused by the presence of libgobject-2.0.0.dylib in Matlab's library search path, as that library is only expected to be present if GStreamer is installed and set up, not otherwise. Most systems won't have that library under /usr/local/lib. Some 3rd party software, maybe from HomeBrew or similar, must have installed it?
Not sure if we can make our logic more robust against this or not.

**Comment by kleinerm** [comment]
Ok, i think i managed to add a hack to the Screen() function for the next PTB beta to avoid these crashes. Works for me, will be part of the next PTB beta update later this month.
