### ISSUE TITLE
Psychtoolbox changing screen resolution on OpenWindow

### ISSUE THREAD

**Issue by UnsignedByte** [Psychtoolbox-3/Psychtoolbox-3#646]
Psychtoolbox changes the screen resolution on the window when opening a new window after having used a second monitor. The screen resolution is not reflected in rect and is causing the mouse to be placed in the wrong position.

**Comment by dcnieho** [comment]
This is an unclear message, do you mean that this happens after you
disconnect the second monitor? When the connected screens change, you
should "clear mex" before running PTB again, that will cause the screens to
be rediscovered and should prevent this

**Comment by kleinerm** [comment]
Yes, please give way more details and a sample script that shows this behaviour. Also, which hardware, graphics card, monitor setup, operating system and version?

Maybe you are on a Apple computer with its awfully buggy macOS, and the switching you observe is part of the heap of hacks we have to use to workaround all its display timing bugs, and what you see is the side-effect of those workarounds. In that case it is pretty unlikely to be fixable, especially not without a big time investment, for which you'd need to contract us. We strongly advise against the use of Apples toys for vision science research.

**Comment by UnsignedByte** [comment]
The issue came up after I was disconnected from the second monitor; now whenever using psychtoolbox even after restart of matlab the new screen will change the resolution of my computer when running.
I have tried setting resolution using PTB as well as `clear mex`, but nothing has solved the problem. I am running on macOS Mojave.

The following is sufficient to show the problem:
```
Screen('Preference', 'SkipSyncTests', 1);
[w, rect] = Screen('OpenWindow', 0,[]);
SetMouse(rect(3)/2, rect(4)/2, w)
```

The cursor on my device will not appear in the center of the screen as the resolution somehow is changed for the screen but not registered to be different in PTB.

**Comment by kleinerm** [comment]
Yep, that's caused on Retina displays by the hacks we have to use to fix all the visual timing brokeness of Apples trainwreck. GetMouse coordinate reporting is also broken for some scaled resolutions, but not others (e.g., 1440x900 works on a 2880x1800 Retina panel, but others don't), because Apple sucks.

The easy thing to do is to disable backwards compatible mode wrt. Retina and always run the onscreen windows at full Retina resolution:

Replace your OpenWindow call by:

PsychImaging('PrepareConfiguration');
PsychImaging('AddTask','General','UseRetinaResolution')
[w, rect] = PsychImaging('OpenWindow', 0);

Everything more elegant would require a lot of work for piling more hacks onto the current ones. That would have to be done for serious money under contract.

**Comment by kleinerm** [comment]
Update: The latest PTB beta does improve mouse-positioning in scaled Retina modes iff you provide the optional onscreen window handle to SetMouse().
