### ISSUE TITLE
FillRect fails on async flips with OpenGL render

### ISSUE THREAD

**Issue by k1o0** [Psychtoolbox-3/Psychtoolbox-3#648]
A few years ago we changed viewing models, using the PTB GL wrappers to load and transform textures with a shader.  This works very well.  We also use Screen's `FillRect` command to draw a sync square in the corner of the screen for recording flips with a photodiode.  A few months ago we noticed that sometimes the sync square doesn't update.  That is, we draw our stimulus, call `FillRect`, then when we call `AsyncFlipBegin` the stimulus shows on the screen but not the sync square.  This happens only on on some flips (see figure).  I have never witnessed the stimulus failing to show up on the screen, only the sync square.  We use asynchronous flips because we do a lot of other things in our main experiment loop.

![image](https://user-images.githubusercontent.com/25670666/76075087-108add00-5fa5-11ea-80b4-acc4796c0627.png)

Some people think this happens more often on older PCs (a few years old, not ancient).  I must stress that the sync square is always drawn together with the stimulus, and all flips are completed.  I have not seen this occur if we use `Flip`, nor if we draw a stimulus without a viewing model using `DrawTextures`.  Our stimuli are pretty simple (no 3D, simple shapes and Gabor patches).  We observe this behaviour across a number of rigs that use different hardware, all running Windows 10 and recent versions of PTB.  PTB does detect these failures and prints the following:
```
INFO: PTB's Screen('Flip', 10) command seems to have missed the requested stimulus presentation deadline
INFO: a total of 21 times out of a total of 376 flips during this session.
```

I've attached a script to give you an idea of the experiment loop.  It isn't stand alone as there is a shader and a fair bit of code for setting up the projection matrix etc. but it shows the stimulus and sync square are drawn to the screen.  

[screenPokePTB.txt](https://github.com/Psychtoolbox-3/Psychtoolbox-3/files/4297927/screenPokePTB.txt) - Script showing how we draw stimuli and sync square 

All other dependencies are here:
[shader.frag](https://github.com/cortex-lab/signals/blob/master/%2Bvis/slimshady.frag)
[shader.vert](https://github.com/cortex-lab/signals/blob/master/%2Bvis/slimshady.vert)
[vis.init](https://github.com/cortex-lab/signals/blob/master/%2Bvis/init.m) - loader for shader
[vis.planeProjection](https://github.com/cortex-lab/signals/blob/master/%2Bvis/planeProjection.m)
[vis.uniSphereTriangles](https://github.com/cortex-lab/signals/blob/master/%2Bvis/uniSphereTriangles.m) - For pseudo-circular projection

We're at a loss as to how to debug this further.  We're not sure why only `FillRect` fails or how this could interact with the OpenGL rendering.

Specs from one of the PCs:
Windows 10
PTB 3.0.16
Intel Core i5-8500 CPU @ 3GHz
16GB RAM
Onboard graphics card Intel UHD Graphics 630

**Comment by kleinerm** [comment]
Hm. Without fully self contained demo, that's difficult to figure out. A few possible culprits:

I'd wrap the whole vis.init() function call into Screen Begin/EndOpenGL. This is what isolates/protects PTB's internally used OpenGL contexts from user code messing things up. E.g., i see your setup code using glBind... commands to bind/unbind buffers, something that changes OpenGL state PTB might rely on itself. Everything inside the Begin/EndOpenGL pair is run inside its own private "user script" OpenGL context to prevent such state bleeding.

If you look at AsyncFlipTest.m, it uses PsychImaging to enable a virtual framebuffer, instead of just using Screen('Openwindow',...); The help of Screen AsyncFlipBegin explains there are various restrictions when using async flips, most of which are lifted if you use the imaging pipeline via PsychImaging. Maybe your code violates some restrictions, maybe not, but the AsyncFlipTest approach would be more on the safe side, and provides a host of other potentially useful functionality.

drawnow; is also suspect: Why is it there? There is some danger of interference between PTB and Matlab wrt. OpenGL, since recent Matlab versions implement their plotting functionality themselves in OpenGL. Mixing plotting with OpenGL can have side effects. You could try to to set the renderer used for such plotting from 'opengl' to 'painters', somewhere in figure properties. Cfe.: https://psychtoolbox.discourse.group/t/displaying-a-matlab-figure-as-a-texture-in-ptb/3078?u=mariokleiner

Then there's the potential of graphics driver bugs. If you only use Screen drawing, one OpenGL context is used. If you use Begin/EndOpenGL for glXXX functions etc. a second OpenGL context is used for stuff inside Begin/End to protect PTB and your code from each other messing up each others OpenGL state. 'AsyncFlipBegin' et al. bring in a 3rd OpenGL context operated by a parallel high priority background thread that does all the async flipping. So with async flips you go from switching between 2 OpenGL contexts on one main thread, to 3 contexts, distributed over two parallel threads. Now this has been tested and should work as is, handing over and synchronizing between the different threads appropriately, but the higher complexity has some potential to unconver/trigger bugs in the OpenGL graphics drivers. Intels driver on Windows are especially bad/buggy in my experience.

**Comment by kleinerm** [comment]
No feedback in ~5 months, so I assume user error. Closing.

**Comment by k1o0** [comment]
Sorry I've been working on other things this past few months.  Thanks for the response, it's difficult to make the demo more self-contained but I could replace the viewing model with identity matrices and try using a simpler shader (although the current one doesn't do anything fancy).

> I'd wrap the whole vis.init() function call into Screen Begin/EndOpenGL

Currently the buffer is set up the we call `Screen BeginOpenGL` on line 92 of `vis.init`, just before binding the buffer.  I tried moving this call so that all of `vis.init` is executed within the OpenGL state but it didn't solve the issue.

> drawnow; is also suspect: Why is it there?

Our wider code uses various MATLAB callbacks to do things like processing UDPs so we use `drawnow` to ensure that the callbacks are executed.  We don't have any figures or GUIs running though.  Removing `drawnow` doesn't solve the issue.

> Then there's the potential of graphics driver bugs

The specs I gave were for my laptop, however most of our experimental rigs use Nvidea NVS 510 by PNY graphics cards, and drive three screens using their Mosaic feature.

> If you look at AsyncFlipTest.m, it uses PsychImaging to enable a virtual framebuffer, instead of just using Screen('Openwindow',...);

We're already using asynchronous flips but not activating PsychImaging.  It's unclear to me how a virtual frame buffer helps but I tried it and it seems to work!  At the moment I'm just looking at the sync square by eye and checking that it's always filled but on my laptop I haven't seen any failed frames yet, whereas it happens frequently without activating PsychImaging.  Assuming this does indeed fix the problem, could you explain what's happening in the normal case and why the virtual framebuffer helps?  It's like black magic to me!
