### ISSUE TITLE
Issues with SimpleMovieDemo 

### ISSUE THREAD

**Issue by fang510** [Psychtoolbox-3/Psychtoolbox-3#675]
Hi,

Recently I have been working on movie playing with ptb3. I have followed the webside guides to switch into a Linux system and tried -nojvm mode. But I still cannot get SimpleMovieDemo running.

After I run 'sudo ptb3-matlab' and type in ''SimpleMovieDemo', the screen just flashed black and returned to the main GUI window. Here are the outputs from the matlab window:

~~~~~~~~~~~~~~~~~~~~~~~~
PTB-INFO: This is Psychtoolbox-3 for GNU/Linux X11, under Matlab 64-Bit (Version 3.0.16 - Build date: Mar 26 2020).
PTB-INFO: OS support status: Linux 5.4.0-42-generic Supported.
PTB-INFO: Type 'PsychtoolboxVersion' for more detailed version information.
PTB-INFO: Most parts of the Psychtoolbox distribution are licensed to you under terms of the MIT License, with
PTB-INFO: some restrictions. See file 'License.txt' in the Psychtoolbox root folder for the exact licensing conditions.

PTB-INFO: Hybrid graphics setup with support for "NVidia Optimus" DRI PRIME-Sync output slaving detected - or so i think?
PTB-INFO: If you are displaying on a video output directly connected to the NVidia gpu, then my thinking here
PTB-INFO: might be wrong. In that case use PsychTweak('UseGPUIndex') to fix me! Otherwise timing might be wrong.
PTB-INFO: If i'm right, then the following assessments hold for your Optimus setup with NVidia's proprietary driver:
PTB-INFO: The custom modesetting ddx of Psychtoolbox for Optimus is not installed, so visual timestamping will be wrong!
PTB-INFO: Therefore visual timing and timestamping will likely be highly unreliable. Please read 'help HybridGraphics'
PTB-INFO: on how to install a custom modesetting ddx in order to fix visual onset timestamping and improve timing.

PTB-INFO: OpenGL-Renderer is NVIDIA Corporation :: GeForce 940MX/PCIe/SSE2 :: 4.6.0 NVIDIA 390.138
PTB-INFO: VBL startline = 1080 , VBL Endline = -1
PTB-INFO: Beamposition queries unsupported or defective on this system. Using basic timestamping as fallback.
PTB-INFO: Timestamps returned by Screen('Flip') will be therefore less robust and accurate.
PTB-INFO: Measured monitor refresh interval from VBLsync = 16.695962 ms [59.894722 Hz]. (50 valid samples taken, stddev=0.018816 ms.)
PTB-INFO: Reported monitor refresh interval from operating system = 16.664722 ms [60.007000 Hz].
PTB-INFO: Small deviations between reported values are normal and no reason to worry.
PTB-WARNING: OpenGL driver seems to use 1-buffering instead of the required double-buffering for Screen('Flip').
PTB-WARNING: This could be a false positive in which case there is no reason to worry, but it could also indicate some problem
PTB-WARNING: with visual stimulus onset timing on your setup, which would impair visual timing and timestamps of Screen('Flip').
PTB-WARNING: If timing matters, I'd recommend performing further diagnosis and potential troubleshooting (read 'help SyncTrouble').
PTB-WARNING: One potential cause for this is that some kind of desktop compositor is active and interfering.
PTB-WARNING: The most likely cause on this NVidia Optimus setup is the use of the proprietary driver, which will massively impair proper timing!
PTB-WARNING: Use the open-source nouveau graphics driver, or install the enhanced modesetting ddx, or do not use the NVidia gpu at all, if you
PTB-WARNING: care about research grade timing. See 'help HybridGraphics' for more info.
PTB-WARNING: This is a one-time warning which will not repeat, even if the problem persists during this session.
~~~~~~~~~~~~~~~~~~~~~~~~~

And from the terminal where I opened up the matlab GUI, it goes:
~~~~~~~~~~~~~~~~~~~~~~~~~~
inux-gnu/gstreamer-1.0/libgstlibav.so': /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

(MATLAB:1922): GStreamer-WARNING **: 21:54:42.250: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so': /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

(MATLAB:1922): GStreamer-WARNING **: 21:54:42.285: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so': /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

It seems to me the problem is with the Gstreamer?? But I have tried several times with uninstall and install, trying to make sure needed plugins are well installed. Could you offer some suggestions? Thank you so much.

I also notice the outputs are more or less similar when I used the -nojvm mode. However, I would have to run Screen('Preference', 'ConserveVRAM', 64);  and Screen('Preference', 'SkipSyncTests', 1); before simpleMovieDemo, then it will go the 3 Gtreamer-warnings above. It seems strange to me as I thought it supposed to be more carefree when going with nojvm mode.

Thank you so much for your time reading this and any suggestion is very much needed!

Fang

**Comment by kleinerm** [comment]
Probably the freetype library used is too old, because your version of Matlab comes with its own outdated version that overrides the version provided by the operating system. An annoying thing that Matlab does, and happens often on Windows and macOS, more rarely on Linux. What Linux distro and version? What Matlab version?

E.g., if you'd be using R2014b, then you could rename (or delete) this file, then restart Matlab:

/usr/local/MATLAB/R2014b/bin/glnxa64/libfreetype.so.6

**Comment by fang510** [comment]
Wow you are just amazing! I just removed the libfreetype.so.6 file and it WORKS! Though I still got some warnings about driver, but I think that is pretty okay for me. 

Thank you sooooo much!

Btw, I ran it on Ubuntu 18.04.5 LTS with Matlab 2016b.

Fang

**Comment by kleinerm** [comment]
Rule of thumb is to pick a Matlab release younger than the OS release date for best chance of plug & play. E.g., Ubuntu 18.04 released in April 2018, so R2018b, R2019a, ... probably the higher the better.

Another thing: You do not need (and shouldn't use) sudo ptb3-matlab, but only ptb3-matlab, no need for admin mode here.
In fact, it would probably cause trouble by writing to some Matlab files in your user directory, but with "root" identity, changing their ownership, so then in future sessions you or your Matlab won't be able to fully access those files as a normal user anymore.

The third thing is that those PTB warnings suggest you use an NVidia Optimus laptop, so without all the extra setup steps hinted at in "help HybridGraphics", presentation timing will be almost certainly wrong. We advise against NVidia Optimus laptops, because they cause all those extra complications.

You can:
0. Not care about accurate timing/timestamps.
1. Only use the Intel graphics chip for proper timing and low-to-reasonable performance.
2. Use the nouveau open-source driver instead of the NVidia proprietary driver and follow the "nouveau" section in the help file to get proper timing and maybe a bit better performance than 1. For further performance optimizations, tedious expert tweaks like the ones in this article https://www.phoronix.com/scan.php?page=article&item=nouveau-410-nvboost&num=1 would be needed.
3. Install the custom modesetting ddx and go through tedious setup iff your distribution still has X-Server 1.19 installed, instead of the more recent 1.20 server, which we don't support with this approach.

Step 3 is painful an with its own downsides, as our help file explains. Step 2 is easy if it works, but lower performance. Step 1 is more simple. Or simply don't use NVidia Optimus laptops, or avoid NVidia in general if you can, as we recommend.
