### ISSUE TITLE
[PsychPython] PsychPortAudio 'Stop' and 'GetAudioData' do not return expected values

### ISSUE THREAD

**Issue by mdcutone** [Psychtoolbox-3/Psychtoolbox-3#715]
When calling either `PsychPortAudio('GetAudioData', ...)` or `PsychPortAudio('Stop', ...)` from PsychPython in audio capture mode, values returned for `absrecposition`, `overflow`, `cstarttime` are not what are expected, always returning zeros.

**To Reproduce**
The following script illustrates the issue for `GetAudioData` using the 'classic' PTB interface:

```
from psychtoolbox import *

def main():
    sampleRateHz = 48000

    pahandle = PsychPortAudio('Open', [], 2, 0, sampleRateHz, 2)
    PsychPortAudio('GetAudioData', pahandle, 10.0)
    PsychPortAudio('Start', pahandle, 0, 0, 1)

    audiodata, absrecposition, overflow, cstarttime = PsychPortAudio(
        'GetAudioData', pahandle, None, 9.9, None)

    # Expected the following values to be anything other than zero. Similar
    # values returned by 'Stop' are also zero.
    print('absrecposition=', absrecposition,
          '; overflow=', overflow,
          '; cstarttime =', cstarttime )

    print('Audio array dims: ', audiodata.shape)  # this works as expected :)

    PsychPortAudio('Close', pahandle)


if __name__ == '__main__':
    main()
```

**Expected behavior**
Values for `absrecposition`, `overflow`, `cstarttime ` should be non-zero in capture mode.

**Desktop (please complete the following information):**
 - OS:  Windows-10
 - Runtime: Python 3.7
 - Hardware: Intel with Realtek audio
 - Version: Psychtoolbox 3.0.16

Edited since I used the wrong return parameter names, issue still stands.

**Comment by kleinerm** [comment]
What happens if you set the `reqlatencyclass` parameter to its default value of 1 instead of 0, ie.:
``pahandle = PsychPortAudio('Open', [], 2, 1, sampleRateHz, 2)``

Difference between Windows and Linux/macOS is that Windows has different sound systems / api's, each with different capabilities and flaws. For the non-default `reqlatencyclass` setting 0, the MME sound system is used, which works everywhere plug & play, but has horrible latency and no timing or timestamping precision at all. Settings of >= 1 will try to choose WASAPI, which is much better wrt. latency, timing etc., but often quite picky about what exact combos of samplerate, number of audio channels etc. it supports.

Probably you don't get meaningful timestamps and such because MME is selected. On Linux and macOS this setting would not affect audio api -- it is ALSA by default on Linux and CoreAudio as the only choice on macOS.

I do remember testing microphone input under Python, and it worked. But the most intense testing on my side is always on Linux, as that is what i recommend strongly to all users.

**Comment by kleinerm** [comment]
Another catch with ``reqlatencyclass`` on MS-Windows, for its default value of 1 == Low latency, precise timing, that i found out just a few days ago when testing on a Windows-10 laptop: As already mentioned, having low latency and high timing precision requires use of the WASAPI sound backend, which does get selected for ``reqlatencyclass > 0``. But WASAPI is often very picky about supported samplerate (+ channels?) combinations. At least on some sound hardware it won't allow sample rates other than the audio device default samplerate (cfe. ``PsychPortAudio('GetDevices')``, unless you choose a ``reqlatencyclass`` of at least 2, to force exclusive use of the audio device by ``PsychPortAudio``, locking out all other running applications from sound. These are limitations of the MS-Windows sound system.
