### ISSUE TITLE
Python PsychHID dropping keyboard events on Windows 10

### ISSUE THREAD

**Issue by isolver** [Psychtoolbox-3/Psychtoolbox-3#745]
On Windows 10, the following Python script _never_ seems to receive / print any PsychHID keyboard events:

```
from psychtoolbox import PsychHID, WaitSecs
import time

ptb_keys = [1] * 256
PsychHID('KbQueueCreate', [], ptb_keys)
PsychHID('KbQueueStart')

stime = time.time()
while time.time()-stime < 30.0:
    while PsychHID('KbQueueFlush'):
        evt = PsychHID('KbQueueGetEvent')[0]
        print(evt)
```

This only happens on Windows 10 - the same script prints 100% of keyboard events on macOS and Linux. Same behaviour when using psychtoolbox 3.0.16 or 3.0.18. Tested using Python 3.6.

Adding a wait to the `PsychHID('KbQueueFlush')` loop greatly improves things:

```
while time.time()-stime < 30.0:
    while PsychHID('KbQueueFlush'):
        WaitSecs('YieldSecs', 0.0001)
        evt = PsychHID('KbQueueGetEvent')[0]
        print(evt)
```

But ~ 0.5 - 1% of kb events are still not reported. Increasing the `WaitSecs` duration to 16 msec reduces the probablilty of dropping an event even more, but testing with 1,000's of keypresses shows that a very small % of events are still being dropped. 

This issue has been[ reported by another person as well](https://github.com/psychopy/psychopy/issues/4318). This user says the drops only occur when using the Python wrapper of PsychHID on win10, not when it is used in matlab. I have not confirmed this.

I've tested this for 1,000's of key presses using a MilliKey button box. The exact same events that are missed by (Python) PsychHID are detected by pyglet, so I do not think this can be a test artifact. 

Thank you

**Comment by kleinerm** [comment]
What you probably want is ``PsychHID('KbQueueFlush', [], 0)``, because if you omit the ``flushType`` parameter as in your example, then flushType 1 will be used, to flush some of the pending input.

What you intend to do with your while loop is just checking if and how many pending events there are, not to get rid of them, so the proper flushType is 0.

That Linux/macOS behave differently, or that a wait changes probabilities of event loss is due to low-level OS differences. On Linux/macOS the default flushType 1 will only clear internal data structures - and ones not actually used by KbQueueGetEvent. 

On Windows it will clear low-level OS input queues, a neccessity due to the different way that Windows handles such input. 

The wait may just allow our internal high priority realtime input processing thread to "snatch" some events from the OS device queue before it gets mistakenly flushed.

Iow., your code is wrong, but by luck it doesn't do harm on Linux/macOS and by luck the ill side effect of the wrong code is minimized by a wait.

As i was skimming at that bug report you mentioned, i saw that there is a misconception. PsychHID's keyboard queue mechanism is driven by an internal realtime high priority background thread, which should not be easily starved of processing time, and the OS itself internally uses even higher priority threads. On a modern multi-core cpu, ie. anything made in the last 15 years, it would be rather difficult to cause the OS or our code to lose any input events due to overloads -- wait commands should not be neccessary. Maybe that bug report also used KbQueueFlush in a wrong way?

It is a good idea to look how PTB's Matlab code uses PsychHID, wrt. call parameters etc., as we generally discourage direct use of PsychHID(). E.g., KbEventAvail.m implements the call for "available input even" reporting.

**Comment by isolver** [comment]
Thank you for the explaination. It would be great to get PsychoPy working correctly with PsychHID keyboard.  

So for win32, `flushType` should be `0`, but for linux and macOS it should be `1`? Or is it safe to use flushType `0` on all operating systems?

psychopy uses `psychtoolbox.hid.Keyboard` in this (distilled) way:

```
from psychtoolbox import hid

dev = hid.Keyboard()

# .... 

dev._create_queue(bufferSize, win_handle=None)

# ....

while dev.flush():
     evt, remaining = dev.queue_get_event()
```

which suffers from the same issue as the code example in the OP. 

> your code is wrong, but by luck it doesn't do harm on Linux/macOS and by luck the ill side effect of the wrong code is minimized by a wait.

I think `psychtoolbox.hid.Keyboard.flush()` is also 'lucky' then; it uses a default `flush_type` of 1 for all operating systems. Does it really make sense to have a default `flushType` that results in dropping events on one OS but not on others?

The documentation for `KbQueueFlush` says this about `flushType`:

```
If ‘flushType’ is 1, only events returned by KbQueueCheck will be flushed. This
is the default.
```

There is no mention of OS differences in how `flushType` is used. 

Thanks again

**Comment by peircej** [comment]
@kleinerm that use of `PsychHID('flush')` was based on the demo you wrote here
https://github.com/Psychtoolbox-3/Psychtoolbox-3/blob/31a309dbd8c74575b4f63c6182663cf4a4d476d1/PsychPython/demos/hidtest_oldschool.py#L27 
So I guess your demo doesn't work on windows? Also, as @isolver suggests, maybe the documentation could make more clear that `flushType=1` deletes events whereas `flushType=0` does not. That would be very hard to intuit from the current docs

> It is a good idea to look how PTB's Matlab code uses PsychHID, wrt. call parameters etc., as we generally discourage direct use of PsychHID(). E.g., KbEventAvail.m implements the call for "available input even" reporting.

I thought you only ported PsychHID, no? But these aren't functions you recommend using? Hmm, that's tricky then 🤔 
Or maybe I misunderstood and the other functions are there somewhere too, in which case maybe you could update the demos to use them as recommended in the new best practice

thanks

**Comment by kleinerm** [comment]
Yes. Even my original example made the mistake, as i just saw, and i guess it spread from there. Sorry.

flushType = 0 is what you want to use for all queries. flushType 2 or 3 would clear the queue of pending events for KbQueueEventGet.

In theory flushType = 1, although still wrong for your use case, should not affect KbQueueGetEvent, it should only affect KbQueueCheck.

In practice, due to MS-Windows low-level input quirks we have to work around, it can affect it, as we just learned. I didn't notice this, because the usage pattern of the function is different on our side.

There is a race between the main thread (python script) clearing out the hardware input queue (a small queue between the OS and our own processing and queuing code, only keeps a couple of dozen items at most iirc. - this is a Windows specific feature), and the realtime thread fetching items from the same hardware input queue used for both KbQueueCheck and KbEventGet. Relative execution timing of the threads, the operating systems own low-level input drivers, and when the human hits a key, will define if our thread for keyboard event recording will get all pending events from the low level hw input queue before it gets cleared, or not. Lots of parallelism between human, keyboard, OS and our threads. That's why a wait, which will change the relative execution timing between the python thread and all other threads, can affect this for the better. That's also why i never noticed the mistake when i tested this on Windows - different typing behaviour, python version, number and speed of processors, OS, keyboard etc. It is statistical and random in that sense.

So flushType 0 is what you want to use to just query for available events.

The reason this is not the default is historical: Somebody contributed some low-level code for KbQueueCheck on macOS to PTB - i think essentially the almost only contribution we ever got to PsychHID from a 3rd party. The design and implementation was not great, but it filled a need and i let it slip, because at that time i still had the hope that if you are not too strict/critical on 3rd party contributors, and don't let them jump through too many hoops before they can contribute, it may create an actual community of contributors. Later on, the implementation was rewritten and extended by myself to Linux and Windows, and then to the KbQueueEvent functionality which is better. Because i value backwards compatibility very strongly and don't like to break existing users scripts without strong reasons (i don't want to turn into Apple, a company i despise for their "approach" to "backwards compatibility"), the default was chosen to be backwards compatible to the original implementations.

I do all my testing of PTB mostly only on Octave (or occasionally on Matlab - Mathworks pays a tiny bit for that wrt. the latest release in a year), but not on Python by default. The assumption is that PsychHID etc. should behave the same way for the same input/use on Octave/Matlab and Python. But one difference is that PsychHID is rarely called directly by user scripts, but almost always through convenience M-File wrappers. So if our wrapper uses the low level stuff differently, none of our users will experience the same behaviour, as is the case here with KbEventAvail.m for getting number of pending events.

I also do most of my work and testing on Linux, because i'm convinced that that is the best OS for most neuroscience use cases, and because that's the system i'm involved with at the low layers, so i can improve it upstream. Windows or macOS only get testing if a new feature is introduced/as needed, to make sure it works on all OS'es or doesn't break compatibility in some way. Or periodic checks when we are paid for it, e.g., by Mathworks. I am still the only person doing 99% of the work for PTB, i am permanently overworked and underpaid, and as most of our business model so far doesn't work, because users like to free-ride instead of contribute, contract work is what keeps the lights dimly on and me way more busy than what is sane.

Wrt. flushType defaults. In principle one could fix such things and make defaults different for Octave/Matlab vs. Python. But then we'd again break backwards compatibility, although there's less code to break on the Python side, given this is all rather new. And it makes debugging/testing harder if the same function calls no longer behave the same on Octave/Matlab vs. Python.

You could send a pull request to fix the wrong code in Psychtoolbox, or i can do it?

**Comment by kleinerm** [comment]
Btw. the .check() functions uses PsychHID('KbCheck'). It is important to note that KbCheck **polls** the **current** live keyboard state, it doesn't use any queues. So If one uses that in a loop with too low frequency, one can miss fast keystrokes . Rarely a problem with humans on normal keyboards. But some button boxes which pretend to be regular HID keyboards have flawed firmware that sends a button press event immediately followed by a release event, instead of a pause of a dozen(s) milliseconds between them, as normal human typing on a normal keyboard would do.

Just in case that has caused bug reports on your side in the past.

**Comment by peircej** [comment]
Thanks. That gets it fixed at our end. Sorry, there was no offence intended - I know how busy you are and I know what it's like writing FOSS. Just, when you said it was us getting the code wrong, I wanted to be clear that we were just following the demos/docs

> Btw. the .check() functions uses PsychHID('KbCheck'). It is important to note that KbCheck polls the current live keyboard state, it doesn't use any queues. 

Yes, not to worry. That's provided in the class for completeness sake. Builder-generated code doesn't use it. I guess we should update the docs on `Keyboard.check()` that to be more clear though. I'll submit a PR for it. 

I might submit a PR with suggested tweaks to the `flushType` docs too. I think that could be clearer that it not only _processes_ event but _removes_ them from one or other queues in the default. I was under the obviously false impression that flush meant "process" (like flush along a pipe) but it actually seems to mean "clear" (like flush a toilet). Again, it's fine, but maybe I can provide some text that improve the clarity (or possibly I'll just make it less clear again! 😆 )

**Comment by kleinerm** [comment]
No worries, no offence taken. Just thought i describe a bit how this bug came about and what my testing approach here is. Sometimes it helps to think if one explains to others, and my rubber duck is out of commission ;)

I will make the change/fix to flushType=0 default in our old wrong demo / PsychPython implementation, because i'm on it anyway and a minor PTB release is upcoming anyway. Docs updates after that welcome whenever you want.
