### ISSUE TITLE
Download/Setup Psychtools cause MATLAB error message for other user on Windows

### ISSUE THREAD

**Issue by jamesgao-nyush** [Psychtoolbox-3/Psychtoolbox-3#757]
The Download or Setup Psychtools script modifies (or just creates a new? ) on the file "C:\Program Files\MATLAB\R20xxx\pathdef.m", and make it lose its ACL inheritance of Users group, only administrators and current console user who have run the script have access to this file. 

When any other user login and launches MATLAB, they will receive a bunch of error messages because the file "C:\Program Files\MATLAB\R20xxx\pathdef.m" is inaccessible now.
![WechatIMG137](https://user-images.githubusercontent.com/54058439/155288403-99a8164d-f579-4051-9173-ffe328db6868.jpeg)

**Comment by kleinerm** [comment]
We don't do anything with the pathdef.m file directly. We just use the ``savepath`` command in its most simple and straightforward form, leaving this job to Matlab. So this is imho either a Matlab bug or problem caused by Matlab, or a configuration problem on your setup. You should probably raise a support request with Mathworks.
