### ISSUE TITLE
Cannot solve error - Invalid mex-file

### ISSUE THREAD

**Issue by Beew4** [Psychtoolbox-3/Psychtoolbox-3#760]
Hi,
I am trying to run a script on MATLAB using the psychtoolbox, but I keep getting this error - 

‘Invalid MEX-file ‘C:\toolbox\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007a\Eyelink.mexw64’: The specified module could not be found.’

The mex file is right there when I go into the MatlabWindowsFiles folder, and I have installed the GStreamer runtime and vcredist. I have also tried the Dependency Walker to find missing .dll files, and everything is added to my path, but I still get the error. Also, when I first load Matlab I get 
'PsychStartup: Adding path of installed GStreamer runtime to library path. [C:\gstreamer\1.0\msvc_x86_64\bin]' 
so I am fairly sure it is running okay.

I am working on a Windows 10 laptop with a 64-bit operating system and a x64-based processor. The MATLAB versions I have is R2020b.

I cannot think of anything else to try so any suggestions would be greatly appreciated.

Thank you!

**Comment by kleinerm** [comment]
As ``help Eyelink`` says, you also need to install the Eyelink runtime libraries (e.g., eyelink_core DLL), which you can get from SR-Researchs customer support website. Otherwise above error message would be expected.

For any further paid advice, or in general to contribute to PTB financially: ``help PsychPaidSupportAndServices``.

**Comment by kleinerm** [comment]
Closing, as the exact same question was asked redundantly on the user forum.
