### ISSUE TITLE
Octave 7 support on Windows

### ISSUE THREAD

**Issue by dcnieho** [Psychtoolbox-3/Psychtoolbox-3#771]
Dear Mario,

For entirely selfish reasons (I am compiling mex files that need a version of GCC newer than that bundled with Octave 6.4), may i request that you update to Octave 7.1 on Windows next time you rebuild the mex files? Or actually, it seems 7.2 is around the corner, so perhaps should wait for that instead? https://octave.discourse.group/t/start-release-process-of-octave-7-2-0/2761

Thanks in any case!
Dee

**Comment by kleinerm** [comment]
Might take a while. Octave 7.1 had problematic bugs which i reported and which will be fixed in 7.2, so not before 7.2.

But then, GStreamer 1.20 on Windows is also a troublemaker with multiple fontconfig related bugs or problems, and either upgrading to GStreamer 1.20 or Octave 7.2 will be backwards incompatible, so needs a 3.0.19 release and churn for the users and myself. And we don't yet have a new MW contract which would pay for any maintenance work or PTB releases in 2022...
