### ISSUE TITLE
Datapixx.mexw64: The specified module could not be found.

### ISSUE THREAD

**Issue by JAQuent** [Psychtoolbox-3/Psychtoolbox-3#772]
Please tell me if that is a bug that you're not responsible for but VPixx is. 

**Description of the bug**
When I tried to run this line (or probably any Datapixx command)
`Datapixx('Open');`

I get the following error:

```
Invalid MEX-file 'D:\MATLAB\PTB\Psychtoolbox\PsychBasic\MatlabWindowsFilesR2007
\Datapixx.mexw64': The specified module could not be found.
```

**Expected behavior**
It should be able to run

**Latop Dell G5 5505:**
 - OS: [Windows Version	10.0.19044 Build 19044]
 - Runtime: [Matlab R2021b]
 - Version [3.0.18 - Flavor: beta - Corresponds to SVN Revision 12862]

**Additional context**
I have just installed the latest VC_redist.x64.exe that I could download as well as gstreamer-1.0-msvc-x86_64-1.20.3.msi. Furthermore, I went into the PTB folder again and ran SetUp. VPixx Software tools are installed. 

Is there any more information you need?

**Comment by JAQuent** [comment]
Thanks for the quick response. I actually have VPixx installed (sorry for not mentioning this).

**Comment by kleinerm** [comment]
You probably need the vcredist_x64_2015-2019.exe, e.g., as bundled in the Psychtoolbox/PsychContributed folder. I'd say either the wrong vcredist is installed, or that libusb0.dll from the VPixx software is not properly installed.

Also, unrelated, but GStreamer 1.20 is not recommended on Windows atm. due to bugs in that version. 1.18.x is what you want, or text rendering may not work at high quality.

If none of this helps, you could either ask VPixx for help, or buy paid support from us for another 30 minutes of my time,
 -> ``help PsychPaidSupportAndServices``.

**Comment by kleinerm** [comment]
No response in 5 days. Closing.
