### ISSUE TITLE
Strange abort conditions behaviour

### ISSUE THREAD

**Issue by mirh** [Psychtoolbox-3/Psychtoolbox-3#788]
**Describe the bug**
I was investigating the dreaded problems with refresh intervals jitter, and just "because" I tried to see what was happening in a VM. 
The thing more or less worked despite not supporting beamposition (not sure if they did not bother to implement the specific raster function, or they aren't supporting the acceleration of the whole directdraw).. except paradoxically it was giving me ***less*** warnings than the native system?

**To Reproduce**
1. Run any code/test on a sleepy/bloated system so much so that it fails the SyncTests. 
2. Somehow get *`PsychGetDisplayBeamPosition`* (*`PsychPrefStateGet_VBLTimestampingMode`* ?) not to work, thus using the presumably inferior alternative fallback
3. ...
4. Profit, now you aren't getting the no-go error anymore.

**Expected behavior**
Since computers without ~~bad OEM or drivers shenanigans~~ the iGPU hampered by C-states can score quite below that, I cannot argue against touching the 20ms cut off value for failing the sync tests.  
But then "not having the measurement of flip intervals like *at all*" seems like it should be an even \*greater\* reason for failure than just high variance. 
Or if not any it shouldn't be that if the numbers (well, the few others you still get) are an absolute disaster you still get a free pass.

**Screenshots**
This is from the native system. Not great at all, and just barely able to make it. ⇓
![NO](https://user-images.githubusercontent.com/9366725/200852533-bbaaebd5-180b-4c8a-990d-850f3d2c436c.PNG)
This is from the VM. Notice how the standard deviation is 0 and passes, yet the graphs are even more of an absolute trainwreck. ⇓
![VM](https://user-images.githubusercontent.com/9366725/200853237-47247a9f-1643-41ae-8aed-b458aa0e9cb7.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 (host), 1803 (guest)
 - Runtime: Octave 6.4
 - Hardware: Intel i7-6500U (+VMWare workstation 16 with guest additions)
 - Version: Psychtoolbox 3.0.18

**Comment by kleinerm** [comment]
PTB detected running in a VM, so disabled all timing tests, so it isn't a surprise no timing trouble is reported etc. It also provided a suitable warning about the VM during startup.

And running with Intel gfx under Windows is known to be broken due to triple-buffering. And PTB detected the brokeness during runtime, although it barely missed it during startup, iow. a false negative - it can happen.

Iow. everything in this issue is expected and also meaningless, as you are doing things you are explicitely told and warned not to do.

Closing as invalid.
