### ISSUE TITLE
Error using PsychPortAudio // Invalid device 

### ISSUE THREAD

**Issue by ClairePleche** [Psychtoolbox-3/Psychtoolbox-3#792]
PTB can't find an audio device and some paths _(see 'file name' in the displayed error)_ seem wrong .

I am coding an experiment to display images and sound. 
No issue was occurring until a few days ago, without modification of the script. I now get an error using  **PsychPortAudio('Open')**. Rebooting MATLAB or the computer doesn't work, although the problem disappeared for a couple of days then reoccurred today **(without modification of the code nor updates)**. 
Before the error occured last week, my sounds were properly displayed.

The error I get is the following:
```
PTB-ERROR: Failed to open audio device -1. PortAudio reports this error: Invalid device 
INTERNAL PSYCHTOOLBOX ERROR
    error:                PsychError_system
    general description:  Error reported by a system call
    specific description: Failed to open PortAudio audio device.
    module name:          PsychPortAudio
    subfunction call:     Open
    file name:            C:\Users\Mario Kleiner\Documents\GitHub\Psychtoolbox-3\PsychSourceGL\Source\Common\PsychPortAudio\PsychPortAudio.c
    function name:        PSYCHPORTAUDIOOpen
    line number:          2877
Error using PsychPortAudio

```

**Desktop (please complete the following information):**
 - Windows-10 
 - MATLAB R2020a
 - Psychtoolbox 3.0.16

**Comment by kleinerm** [comment]
Hello,

as a side note, Psychtoolbox 3.0.16 is end-of-life since years and no longer supported in case of trouble. Also, in general we recommend Linux (Ubuntu 22.04-LTS at this point) for demanding paradigms which may be timing sensitive.

For up to 30 minutes of advice please post your paid support authentication token, cfe. help PsychPaidSupportAndServices for the process. Also see our special discounted christmas offer: [Get support memberships for 99 Euros + tax only! Limited offer!](https://psychtoolbox.discourse.group/t/get-support-memberships-for-99-euros-tax-only-limited-offer/4712/1)

Best,
-mario

**Comment by kleinerm** [comment]
Ok, closing as "User doesn't care".
