### ISSUE TITLE
alternative RPiGPIO mex function

### ISSUE THREAD

**Issue by stevevanhooser** [Psychtoolbox-3/Psychtoolbox-3#810]
On my Raspberry Pi 4B, RPiGPIOMex is producing a segmentation fault whenever I try to read or write a pin.

Calling raspi-gpio via system is way too slow for psychophysics.

I made two versions of the RPiGPIO mex function that uses the pigpio library https://abyz.me.uk/rpi/pigpio.

One has to first install [pigpio](http://abyz.me.uk/rpi/pigpio/download.html):

```
wget https://github.com/joan2937/pigpio/archive/master.zip
unzip master.zip
cd pigpio-master
make
sudo make install
```

I recommend the RPiGPIO_pig, which does not require starting a daemon. The mex program starts a daemon the first time it is called.

For RPiGPIO_pigdif, one must start the pigpio daemon on the command line before calling it

`pigpiod`

I did not have time to implement the PWM functions, but the read/write pins works at sub-millisecond speed. The pig version does not implement wait for edge because the library does not implement it in a single-call manner. 

Both mex files could be improved to include PWM and pig could include wait-for-edge with some extra work.

**Comment by kleinerm** [comment]
I think I found and fixed that (for sudo octave, ie. in root mode) in my master branch. Crash happened on my RPi2B as well, something must have changed in some libwiringPi release a while ago. See:
https://github.com/kleinerm/Psychtoolbox-3/raw/master/Psychtoolbox/PsychBasic/Octave3LinuxFilesARM/RPiGPIOMex.mex
for a new mex file to test.

That said, yeah, wiringPi is deprecated and no longer included in RaspberryPi OS 11+, so your attempt at a rewrite is a good initiative. Btw. all the needed libraries, tools, development files are already available as package, installable via:
`sudo apt install pigpio`

**Comment by stevevanhooser** [comment]
Awesome, thanks. I agree, it's not ideal to run as root. 

It's amazing that PTB runs so well on the Raspberry Pi. Seems like a great option when there's not a need for too many textures (I imagine it would fail at sooner point than a real computer with a powerful video card.)

**Comment by kleinerm** [comment]
On Fri, Aug 18, 2023 at 10:55 PM Steve Van Hooser ***@***.***>
wrote:

> Awesome, thanks. I agree, it's not ideal to run as root.
>
Did you test the performance/latency difference between using the client ->
daemon mode vs. direct mode?
I looked at the code of wiringPi vs. pigpio. It appears certain
functionality is simply not possible without root permissions, but wiringPi
implements a fallback for non-root (accessing low-level hardware
functionality via the Linux /dev/gpiomem device instead of the /dev/mem
device which needs root permissions) with limited functionality, whereas
pigpio does not have such a fallback and just bails out for non-root. I
guess their solution is the daemon. The implementation is low-latency, and
afics if one launches the daemon with the optional -c 256 flag, it will
also switch to realtime scheduling. But ofc. the daemon will have some
higher overhead or jitter, question is if it really matters for typical
neuroscience use.

I guess one could also try to merge both files into one, which will use
direct mode or daemon mode, depending on geteuid() returning root (0) or
non-root (> 0).

Anyhow, this work has already eaten up over 10 hours of unpaid extra work
time, so I'll leave it at that for the time being.

> It's amazing that PTB runs so well on the Raspberry Pi. Seems like a great
> option when there's not a need for too many textures (I imagine it would
> fail at sooner point than a real computer with a powerful video card.)
>
A very talented and experienced developer (former Eric Anholt, now Emma
Anholt) worked on the original open-source graphics and display drivers for
the first few years. Nowadays a bunch of people and Linux companies like,
e.g., Igalia are paid by the RaspberryPi foundation to continue and refine
that work. I also spent about 2 months of unpaid work time refining the RPi
display drivers for neuroscience use, specifically adding Linux kernel
driver functionality to improve visual stimulation timing and timestamping.
It's not quite as good as what I could do for Intel, AMD, NVidia graphics,
but still accurate to an error of at most one vblank duration ie. < 1 msecs
worst case, probably better than 0.1 msecs on average iirc. Timing-wise
better than what most typical high-end Apple macOS machines can do.

So it should be quite usable by design, within the hardware limitations, as
long as nobody messes up some critical component of the software stack.

Available system RAM is the limiting factor for textures, and nowadays I
think you can have Pi's with 8 GB RAM. And the gpu allows for most PTB
functionality for dynamically created stimuli to work, even more so the RPi
4 / 400 VideoCore-6 gpu.

A weak point right now is multi-display, which was never tested by myself,
and has limitations. At least multi-X-Screen mode may not work well, but I
guess not many would use that.

Right now, I have no idea how many labs actually use the Pi with
Psychtoolbox. I thought it would prove quite popular, especially if digital
i/o is needed, or other hardware interfacing, or if cost is an issue. But
by now I only know for sure of maybe 4 labs that use it, including yours.

**Comment by stevevanhooser** [comment]
> Did you test the performance/latency difference between using the client ->
> daemon mode vs. direct mode?
> 

I don't think so. At first, I thought the daemon was the only way to do it and implemented that, and then found the other library. It's really fast (10e-5 seconds on the RPi4B). I had the same worry as you, would the daemon ever get stuck if the Pi was really busy with display tasks.

Thanks for building the Pi video interface and hardware, it's really useful.
