### ISSUE TITLE
Minor NeuroDebian instructions distributed over two web pages instead of one.

### ISSUE THREAD

**Issue by toniklenk** [Psychtoolbox-3/Psychtoolbox-3#815]
I just installed PTB on Ubuntu via the installation instructions here ( http://psychtoolbox.org/download.html ), stated Matlab and and PTB wasn't there. After searching for 30 mins for a solution, it turns out there is a second tutorial on installing PTB on Ubuntu at this localtion ( http://psychtoolbox.org/linux ) and only there the specific command to correctly start matlab for the first PTB session is given.

Please merge these tutorials.

**Comment by kleinerm** [comment]
The `ptb3-matlab` command is also described on NeuroDebians matlab-psychtoolbox-3 download page, where one would generally expect NeuroDebian specific instructions.

There's certainly room for improvements in our documentation, I agree on that. But due to the severe lack of funding by our users, I am always short on work time, especially for things that don't lead to inflow of money. Maybe you could send us a pull request with the specific documentation improvements you'd like to see?

**Comment by kleinerm** [comment]
Sort of done, closing....
