### ISSUE TITLE
mexmaca64 

### ISSUE THREAD

**Issue by julovi** [Psychtoolbox-3/Psychtoolbox-3#835]
**[For commercial support for bug reports, click this link](https://www.psychtoolbox.net/license-key)**

**Describe the bug**
SetupPsychtoolbox fails in M1 MacOS 14.4.1, with:

 Removing the quarantine flag from our mex files to workaround macOS brokeness failed! Error was: zsh:1: no matches found:
/Some_path/Psychtoolbox/PsychBasic/*.mexmaca64 

**To Reproduce**
1. Download 'Psychtoolbox-3-3.0.19.10.zip'
2. Unzip
3. Run SetupPsychtoolbox() from Matlab (r2024a)

**Expected behavior**
A correct installation of the program

**Desktop (please complete the following information):**
 - OS: MacOS 14.4.1/M1
 - Runtime: Matlab (r2024a)
 - Hardware M1
 - Version Psychtoolbox-3-3.0.19.10]

**Comment by henryjburg** [comment]
I just ran into this issue as well, it isn't mentioned on the download page specifically but it is mentioned on the [requirements](http://psychtoolbox.org/requirements.html#apple-macos---not-recommended) page that MacOS is generally not recommended and unsupported **entirely** on Apple Silicon (M1 onwards).

I understand the development team not supporting MacOS now due to insufficient resources, but it also seems they are generally opposed to Apple's hardware and software, so unfortunately PsychToolbox will probably never be supported on newer versions of MacOS.

My lab is looking into trying to find another device to setup and run PsychToolbox on.

**Comment by kleinerm** [comment]
What a surprise. It's not supported yet on Apple Silicon. News about Apple Silicon in a few days:

https://psychtoolbox.discourse.group/t/vss-2024-satellite-on-psychophysics-software-with-matlab-next-monday/5352

**Comment by HaolunLUO** [comment]
> I just ran into this issue as well, it isn't mentioned on the download page specifically but it is mentioned on the [requirements](http://psychtoolbox.org/requirements.html#apple-macos---not-recommended) page that MacOS is generally not recommended and unsupported **entirely** on Apple Silicon (M1 onwards).
> 
> I understand the development team not supporting MacOS now due to insufficient resources, but it also seems they are generally opposed to Apple's hardware and software, so unfortunately PsychToolbox will probably never be supported on newer versions of MacOS.
> 
> My lab is looking into trying to find another device to setup and run PsychToolbox on.

Very helpful
